### ISSUE TITLE
[BUG] Laundry tile is not displayed in the Campus Resources section for university student users

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#108]
**Describe the bug**
Laundry tile is not displayed in the Campus Resources section for university student users

**To Reproduce**

1. Instal Illinois app
2. Complete Onboarding steps and
2. Select Student user on "Who are you screen" and verify his identity
3. On Home screen, the Campus resources section doesn't display Laundry for student user

**Actual Result**
Laundry tile is not displayed in the Campus Resources section for university student users

**Expected behavior**
For student users, the laundry option should display

**Smartphone (please complete the following information):**

Device: [e.g. Android, iPhone]
-Version [e.g. 2.2.18]

**Comment by TodorBachvarov** [comment]
@Priyaravi8 The "Laundry" is visible only if the user is marked as "housingResident" ("HousingResidentStatus":true). Which also means that the user should be IlliniCashEligible:true. Does this appears for your account in the previous versions of the app (since when do you observe this behaviour). Probably your account settings should be checked.
