### ISSUE TITLE
[BUG] "Events For You" curation seems broken

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1171]
For Illinois app v3.0.72

**Describe the bug**
The selection of events in the Events For You section of the home screen doesn't match preference settings.

In my case, I am getting a selection of events from the "Academic" category. But I do not have Academic selected as a preference. 

I do have Entertainment selected as a preference, but the app doesn't show me any events from the Entertainment category. (In the "Events For You" section.)

At the bottom of this section are the words "Because of your interest in: academic". 

**Additional Problems**
- The curated events are not sorted by date.
- The curated events include academic events in the distant future (e.g., "Instruction Ends May 04"), but does not include academic events that are sooner (and therefore even more relevant).
- When I did specify an interest (I chose "Entertainment"), Events For You continued to show me a selection of Academic events, and no Entertainment events. And the statement at the end of the section continued to say "Because of your interest in: academic". 
- It seems odd that "academic" is not capitalized, when it is capitalized in the Settings.

**To Reproduce**
1. Go to _Home_ screen
2. Scroll to _Events For You_ section

**Expected behavior**
The event categories in the curated section should match the categories selected in Settings > Personal Information > Your Interests.

**Screenshots**
![Events for You 1 copy](https://user-images.githubusercontent.com/66988329/147984126-23e3585b-ff0f-438e-8f6e-e9f88c3b1f63.jpeg)

![Events for You 2 copy](https://user-images.githubusercontent.com/66988329/147984132-a5fb0994-58ef-4c68-b36d-9cefe8946fb6.jpeg)

**Smartphone (please complete the following information):**
 iphone 11
 ios 15.0.2

**Additional context**
I asked two other people to test this. They selected some categories in Settings > Personal Information > Your Interests.

The events they got under Events For You seemed random, and did not match their categories.

Also, they did not get an end line saying "Because of your interest in: <category>"

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,

Here are my detailed comments regarding the issues that you described:

1. Main problem:

> The selection of events in the Events For You section of the home screen doesn't match preference settings.
This is fixed. The app was not respecting the categories that the user had been selected in "Manage My Interests" -> "Categories"

2. Additional problems:

> The curated events are not sorted by date
This is fixed.

> The curated events include academic events in the distant future (e.g., "Instruction Ends May 04"), but does not include academic events that are sooner (and therefore even more relevant).
The app requests the Events service based on user's selected categories and tags ("Manage My Interests"). If the Events service returns more than 5 events, the app selects 5 random events and (since v.3.1.12) sorts them ascending by start date. This is the logic of showing these events on the home panel.

> When I did specify an interest (I chose "Entertainment"), Events For You continued to show me a selection of Academic events, and no Entertainment events. And the statement at the end of the section continued to say "Because of your interest in: academic".
The first part is fixed. As regards to the second part - "Because of your interest in: ..." - this label is shown if user has selected favourite tags (in "Manage My Interests") and some of these tags match with some of the tags fo this specific event. So, for example if you have selected tag "academic" and an event has tag "academic", the label "Because of your interests in: academic". 

> It seems odd that "academic" is not capitalized, when it is capitalized in the Settings.
Important note - "Categories" are different from "Tags". So, the not capitalized "academic" is a tag which you have selected in "Tags" ("Manage My Interests") which is different from "Academic" category from "Categories".


All of these which are issues are fixed in 3.1.12. Please test and let us know if you face any other problems.

**Comment by joegrohens** [comment]
I confirm that the "Events For You" section now respects user _interest_ settings.
In v3.1.14 the "because of your interest in" line does not appear unless a relevant event is shown. 

Thank you for explaining the behavior of the "Events For You" feed. I will mention this in user documentation at some point.
