### ISSUE TITLE
[BUG] "Saved" message language not accurate/consistent

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1235]
Two problems:
1) "Saved" message language for Campus Guide refers to calendar
2) Saving a dining location gives no message at all

Option 1: Always display a message, make the language generic to work for all saves
     This starred item has been added to your saved list and if it is an event, also your calendar.
Option 2: use a different message for non-event saves 
     For events, leave as is
     For non-events, change to This starred item has been added to your saved list.

**To Reproduce**
1. Go to a card in the Campus Guide that has a star option, tap the star
2. Go to a dining hall, , or to a dining hall, tap the star

**Comment by dobromirdobrev** [comment]
Hi @kpecknold ,

We implemented Option 1 for the first problem. This is fixed in version 3.1.13. Please verify.

As regards to the second problem - this is not true. Saving a dining location does give a message. But please note that this message ("This starred item has been added ...") is shown only the first time when user stars an item. On the next ones, the app does not show this message.

So if your first starred item is dining, the message will be shown.
