### ISSUE TITLE
[BUG] Groups - not alphabetized

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1239]
**Describe the bug**
In My Groups - All of the groups I added today are properly alphabetized, but groups I have had for several weeks are at the bottom of the list, not alphabetized. Please check alphabetization to ensure entire list gets done.

In All Groups, also no alphabetizing is happening.

I think both should be alphabetized. 

iOS version 3.1.11

**Comment by dobromirdobrev** [comment]
Hi @kpecknold ,
There was an issue with case sensitive sorting of groups. This is fixed in version 3.1.14.

Other than that, please note the following:
1. First the groups are sorted by category and then by name
2. For "My groups", first are displayed the groups that the user is member or admin and below are the groups the the user is pending to become a member.

**Comment by kpecknold** [comment]
I think it would be more user-friendly to sort groups in "My Groups" alphabetically, regardless of category.

**Comment by kpecknold** [comment]
User feedback - Please alphabetize My Groups - don't use the category.  @pmarkhennessy

**Comment by kpecknold** [comment]
Confirmed fixed in 4.2.47
