### ISSUE TITLE
[BUG] Twitter feed drops elements in display of posts.  

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1322]
**Describe the bug**
This bug report came from August Scheiss, director of social media in Public Affairs. She is the person in charge of the Illinois Twitter account.

Hi Isaac,
 
Hope you’re staying warm today! We wanted to reach out about the Twitter feed on the Illinois app. We LOVE it! Thanks so much for featuring it. 

There are a few instances where it doesn’t always show the spacing, videos, or link previews in the same way it appears on Twitter (attached are a few examples). Is there anything we should do on our end? It seems like images always show correctly, but of course, we occasionally share video and link previews.
 
Thanks for any advice!
August
 
AUGUST SCHIESS Director of Social Media   Public Affairs | University of Illinois Urbana-Champaign 507 E Green St, Suite 318 | M/C 428 Champaign, IL 61820 | [illinois.edu](https://illinois.edu/) 217.300.4181 | [aschiess@illinois.edu](mailto:aschiess@illinois.edu)

I am attaching a file containing August's screenshots. They show the difference between the web view of three posts compared to the Illinois app view.

[bug report - Twitter feed .pdf](https://github.com/rokwire/illinois-app/files/8026650/bug.report.-.Twitter.feed.pdf)

**Comment by mihail-varbanov** [comment]
I managed to fix just part of the issues because Tweeter public API is a real pain.

1. The display of the tweet with orange and blue tiles is fixed. However we are unable to properly handle the IlliniFridays hashtag link.

2. We are still unable to display image previews of links.

3. The video preview image is handled.

The above is available in version 3.2.18.
