### ISSUE TITLE
[BUG] Forget my information navigates to privacy level setting and blank Home screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1392]
**Describe the bug**
App displays blank Home screen once the user confirms to "Forget my information" and updates his privacy level setting

**To Reproduce**
1. Install the Illinois app
2. complete onboarding with Privacy level 5 and sign in with user net id with role University student
3. Navigate to the Setting screen
4. Tap on the button "Forget all my information"
5. Confirm "Forget my information"

****NOTE** - once the user confirms to "Forget my information", Update your privacy level screen is displayed - IS this correct behavior? Please confirm**

**Actual Result**

1. Once the user confirms to "Forget my information", Update your privacy level screen is displayed. 
2. Set the privacy level to 5 and tap on "Set my Privacy" button
3. Home screen is displayed with blank white. No information is displayed.

**Expected behavior**
Privacy center screen should be displayed after the user confirms "Forget all the information". The home screen should display all the information.

**NOTE - This issue happens only for the first time when the user installs the app and proceeds with the steps as mentioned.**

**Smartphone (please complete the following information):**
 - Device: [e.g. android]
 - Version [e.g. 3.1.15]

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,

I confirm that showing "Update your privacy level" screen is expected behaviour. This is because the user has removed all his information and the app requires a privacy level to operate.

As regards to the blank screen - we were not able to reproduce it. But we found and fixed a crash that may caused it.

This is fixed in version 3.2.27. Please check and let us know if the issue is fixed.

P.S. I reopen this issue because github closed it automatically.

**Comment by Priyaravi8** [comment]
Retested this issue and it is fixed in version - 3.2.27.
