### ISSUE TITLE
[BUG] Group details don't load for new private group

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1607]
This morning, 5/4/2022, Using 3.3.22I encountered the following error.

1. Create a new private group
2. Ask a user to search for it 
3. They will find the group, but when they tap into it, **the group details don't load** and they can't request to join 

I asked several users to try joining my new, private group and they all got the same error.  

After I changed the group to public, they were able to see it, tap in and request to join.   
The group is called "University Housing ET"

I have changed this group back to private so you can try to search for and request to join this exact group.

**Comment by pmarkhennessy** [comment]
@kpecknold I found the same thing this morning

**Comment by mdryankov** [comment]
Hi @kpecknold @pmarkhennessy  and thanks for the report! It was a nice catch!

The reason of this issue is the new hidden group feature and a regression bug. 
At the moment this is fixed and deployed on Dev -Ref:  https://github.com/rokwire/illinois-app/issues/1607

My advice is for an intensive test before transition to Test & Prod environments, because the current state contains changes to notifications & polls as well.

**Comment by kpecknold** [comment]
@Priyaravi8 Can the QA Team help to test this?

**Comment by pmarkhennessy** [comment]
@Priyaravi8 @kpecknold The updated BB is only in Dev at the moment and needs to be deployed to Test and Prod. You can test it with the last 3.3.x Dev version from the General channel.

**Comment by vburgett** [comment]
@kpecknold I could search, find, and see the details for the private group "University Housing ET." Do you agree this is no longer an issue and can be closed?
