### ISSUE TITLE
[FEATURE] Settings UI changes

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#1670]
**University Monday 2022/05/23** / 2022/05/23

6.4 Attached settings UI changes. Let me know if anything is unclear, but I think there is enough here to get the idea and implement the new look and feel.

![settings1](https://user-images.githubusercontent.com/5978121/170471928-6e00d166-cce3-4277-8bc7-0ca901b7624c.jpg)

**Comment by vburgett** [comment]
Would "Delete My Account" be the same as "Forget All My Information" and "Delete My Personal Information" that are in the app now?

I added "My Push Notification Settings" to the dropdown UI (since "Notifications" are reminders from Athletics, To-Do List, Rings, Groups, Events, etc. available via the bell icon on every screen).

Do you think "My Profile" needs to be repeated in the Settings dropdown? It's on every page with the profile icon and on the settings landing screen when you are logged in. I vote for not including "My Profile" in the settings dropdown.
![Screen Shot 2022-05-27 at 10 35 51 AM](https://user-images.githubusercontent.com/1044905/170732124-c29641fd-316d-439b-a30c-94cd6f8ebf6d.png)
.

**Comment by dobromirdobrev** [comment]
**Re: University Monday 2022/05/30** / 2022/05/31

1 Dobromir, the three main panels icons at the top for:

1.1 Profile

1.1.1 Add to the profile panel a drop down at the top like we have in settings with:

My Profile
Who You Are
My App Privacy Settings (see the attached image)

1.1.2 The default landing panel is the My Profile Panel

1.1.3 Remove My Profile, Personal Information and My App Privacy Settings from the settings drop down.

1.2 Notifications

1.2.1 Add to the Notifications panel a drop down at the top like we have in settings with:

My Notifications
My Notification Preferences (this is the panel we get to from privacy center at the moment)

1.2.2 Remove My Notifications from the settings drop down

1.3 Settings

1.3.1 Add to the drop down My Calendar Settings

1.3.2 The Settings drop down should now only contain: 

Settings Section
My Interests (from the original Manage My Interests panel this will have only categories and tags)
My Food Filters
My Sports Teams (from the original Manage My Interests panel this will have just the sports items)
My Calendar Settings (The two calendar items from the current Personal Information panel)

1.4 The Profile, Notifications and Settings panel should have a back arrow in the title bar.

![MyAppPrivacy](https://user-images.githubusercontent.com/5978121/171092984-a6783ef5-0a7a-483d-b525-a0ebddbf0e82.jpg)

**Comment by dobromirdobrev** [comment]
Re: University Monday 2022/05/30 / 2022/06/01

1.2 Settings

1.2.1 Can you make the Dropdowns before it is invoked, for Settings, Notifications and Profile be Orange including the drop arrow. For example, when I enter My Profile the "My Profile" text that appears will be Orange and the down arrow. N.B. The behaviour when it is dropped down is already perfect.

1.2.2 Ongoing

**Comment by dobromirdobrev** [comment]
Done in version 4.0.21
