### ISSUE TITLE
[FEATURE] App shows Supports Wallet in App Store

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#1851]
**Is your feature request related to a problem? Please describe.**
Currently, the app is showing "Supports Wallet" in https://apps.apple.com/us/app/illinois/id1476075513. This needs to be removed based on a Slack conversation with @vburgett and @joegrohens.

**Describe the solution you'd like**
If this is a source code configuration change, please remove "Supports Wallet" from the source code. I briefly looked at AppStoreConnect and couldn't find a configuration related to this there. If this is related to build configuration, please let me know what needs to be done and I can take care during the build and submission process. Thanks.

**Describe alternatives you've considered**

**Additional context**

**Comment by sandeep-ps** [comment]
Hi, @pmarkhennessy, when you get a chance, could you please have a developer take a look at this question? Thank you.

**Comment by mihail-varbanov** [comment]
Hi @sandeep-ps,

"Supports Wallet'' appears for the Illinois app on App Store because "edu.illinois.rokwire.ios" App ID  had this capability enabled in "Certificates, Identifiers & Profiles" section in Apple Development Portal. I remember that there was a time we were attempting to add Illinois ID Cards to the Apple Wallet. Later we gave up this idea and I removed the relevant capabilities from the app entitlements (the Xcode project) but I obviously had forgotten to do this in the Apple Development Portal either. Anyway, I turn this off now so "Supports Wallet' should get removed from the App Store on the next app submission.

**Comment by sandeep-ps** [comment]
Thanks, @mihail-varbanov. This is great! Shall I close this issue, or do you need to link in a commit?

**Comment by sandeep-ps** [comment]
Thanks, Misho. I will assign this to me for review after the submission and closing. Thanks again.

**Comment by vburgett** [comment]
I'm still seeing "supports wallet" with this latest release. Any thoughts on why? @sandeep-ps https://apps.apple.com/us/app/illinois/id1476075513

**Comment by sandeep-ps** [comment]
Hi, @vburgett, Sorry, I don't think I have an answer to that question. Since there was nothing specific to be done during the build stage as per the conversations in this issue, I proceeded with the build process as usual.

Hi, @mihail-varbanov, Would be able to explore this more?

**Comment by mihail-varbanov** [comment]
The last thing I can think off is to remove any references to PassKit.framework. If this does not help I really have no idea what else I might do. This fix is available in support/4.1 branch and develop so we will check if this fixes the issue on next app submission.

**Comment by sandeep-ps** [comment]
Hi, @vburgett, 
The "Supports Wallet" tag is no longer present. Please see https://apps.apple.com/us/app/illinois/id1476075513.  

Thanks, @mihail-varbanov.

I'm closing this issue.
