### ISSUE TITLE
In Favorites, My Dinings, My Athletics, My News, My Notifications, My Campus Guide are inactive

### ISSUE THREAD

**Issue by RokBill** [rokwire/illinois-app#1896]
I'm using Illinois App Version 4.0.44.

When I tap on any of the above mentioned items in Favorites, nothing happens. I was expecting to see my teams, in Athletics, for instance.

**Comment by vburgett** [comment]
For scenario B, let's change the default "My" widget wording under **Favorites** to "Tap the ⭐︎ on items in [Dining] for quick access here." Please make the section name a link to the relevant category home panel. (Please note "Dinings" should be "Dining")

When you access a "My" section under **Browse**, please repeat that same text and link when those screens are blank.   

![Screenshot_20220713-090014~2](https://user-images.githubusercontent.com/1044905/178753965-fad634cd-2bfa-40ae-a6a5-39b7113d8981.png)
![Screenshot_20220713-090029](https://user-images.githubusercontent.com/1044905/178753971-2a5293ab-70e3-457f-afd2-335e7349f2bb.png)

**Comment by mihail-varbanov** [comment]
Implemented in version 4.0.52

**Comment by vburgett** [comment]
The Athletics Teams Favorite widget links to the corresponding screen but I'm not sure where it's linking from. Can the section text be formatted like the others? 

The Athletics Teams Favorite widget and Browse section leads to a setting (similar to My Notifications). After favoriting a few teams, I expected something to change on my Favorite widget. It did not. I would remove the Favorite widget and Teams Browse section since it is a setting covered by the Settings gear icon and not really an app section. 

![Screenshot_20220717-125431](https://user-images.githubusercontent.com/1044905/179418738-02d08336-6069-4e04-921a-66515b8a0321.png)

**Comment by mihail-varbanov** [comment]
@vburgett, I believe the latest fix in #2102 resolved your last issue?
