### ISSUE TITLE
[USABILITY] Language in the Customize screen v4.0.53

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1905]
Vanessa - 

Please review - if you agree with any of this you could send to Mark.

Some of the language could be better on this screen.

Go to **Customize**

![your favorites](https://user-images.githubusercontent.com/66988329/177657409-ac7159c8-c82f-49a2-b181-570d56836129.png)

**Your Favorites**

Is it inconsistent to mix third person (your favorites) and second person (my groups)? When do you use one voice versus the other? Could this be "My Favorites"? But then it seems that you are talking to yourself. Could it be "Your Groups"? Then it seems like the app is talking to you, which makes sense, and is consistent with command voice: "Tap the star" is implied second person.

> Below is the content currently on your favorites screen. To reorder your favorites, tap, hold, and drag an item. To remove an item from your favorites, click on the star.

Capitalize "Favorites screen" (it is a named screen, proper noun). Change "click on the star" to "tap the star". (It's not mouse-based. Also, "click" is preferable to "click on".)

**Unused Favorites**

![unused favorites](https://user-images.githubusercontent.com/66988329/177657611-b05553da-99a2-4a03-876f-ad346f250b43.png)

1. The heading "Unused Favorites" suggests that the items below are someone's favorites. But if they are down below, they are exactly not favorites. Oxymoron.

- It is not clear (to a new user) whether they are there because they used to be favorites and were removed. Or because were they never favorites in the first place.

- Possible alternate headings: "Unfavorited Items", "Not Favorites", "Unfavorites", "Former Favorites", "Removed from Favorites", "Other Items" (the last is my, er, favorite)

2. The instruction text below the heading could be more concise and standard in usage.
> To add one of the below items to your favorites, click on the star.

_Change to:_ Tap the star to add items below to your favorites.

**Comment by vburgett** [comment]
@joegrohens thank you for this input and explanation. 

The tools should stay user centered ("My Groups") rather than us talking at the user ("Your Groups"). The logic would be the tools are in first person "My Groups" while the instructions are in second person "your groups." So I would agree with changing "Your Favorites" to "My Favorites" as one option. 

Overall I suggest the attached. Are there still voice or style issues from your perspective?

![CustomizeFeedback2022-07-06](https://user-images.githubusercontent.com/1044905/177860412-f681f4e6-1712-432f-9923-5dbb251ec0d1.jpg)

**Comment by joegrohens** [comment]
Thank you. That sounds good.

Joe

**Comment by vburgett** [comment]
@pmarkhennessy this ticket's request is now finalized: 
![CustomizeFeedback2022-07-06](https://user-images.githubusercontent.com/1044905/177868042-138a6f59-14d5-45d6-b3c7-62ff3c97df6f.jpg)

Under Favorites > Customize:

Change to “Current Favorites”

Change to “Tap, hold, and drag an item to reorder your favorites. To remove an item from Favorites, tap the star.”

Change to “Other Items to Favorite”

Change to “Tap the star to add items below to Favorites.”

**Comment by vburgett** [comment]
I have watched a couple of users interact with "customize" in 4.0.53, noting how they think the customize screen is broken because they missed the "hold" part. The suggested, more succinct text and bolding of **hold** should improve this user experience.

Change to “Current Favorites”

Change to “Tap, **hold**, and drag an item to reorder your favorites. To remove an item from Favorites, tap the star.”

Change to “Other Items to Favorite”

Change to “Tap the star to add any below items to Favorites.”

**Comment by vburgett** [comment]
Updated. @joegrohens please close the ticket if you agree. Thank you!
