### ISSUE TITLE
Laundry information [USABILITY]

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#1916]
Describe the usability issue
After working with @vburgett and @kpecknold 
Laundry information is hard to find, hidden under multiple clicks through "Campus Guide". Please make the following changes:

-	Browse screen: add Laundry alpha order under “Groups”
o	Browse screen text should read “View laundry locations and washer/dryer availability.”
 
-	Map: Add “Laundry” as an option in the Map dropdown menu for those who have access to Laundry (not everyone)
o	If this is possible, under “Browse > Laundry” keep the list view and remove the “List” and “Map” links in the header
 
-	Under specific Laundry locations:
o	Change the selected star to an orange star (not navy)
o	Delete the second instance of the word “Laundry” located on the white background (below the navy header that also reads “Laundry”)
o	Align favorite star with the location header. If possible, slightly decrease the laundry location header font size to accommodate star fitting to the right of it.

-	My Laundry screen:
o	Update default “Whoops” message to “Tap the [star] on laundry locations to quickly find them here.” 
o	Once favorited laundry locations show up under “My Laundry,” add a “View All” link at the bottom of the “My Laundry” screen that leads to the complete laundry location list (Browse > Laundry)

**Comment by mihail-varbanov** [comment]
This issue is handled in 4.0.50.

> ⦿ Browse screen: add Laundry alpha order under “Groups”

It is not as simple as described above.

In Browse we can add Laundry in an existing section, or create a new section. The fact that  you talk about the alphabetical order makes me think that you mean section because only sections are alphabetically ordered. That's why I created a new Landry section with a single entry inside called also Laundry. You can update these titles as you want, or we can add the Laundry entry in an existing section (as it was in the "Campus Resources" section).

Also, in order to look similarly to the rest of Browse panel content we need a corresponding widget for that entry. That's why I created "Laundry" widget for the Favorites panel that is pretty similar to "My Laundry" but displays the entire laundry content (not just the favorite laundry).

> ⦿ Map: Add “Laundry” as an option in the Map dropdown menu for those who have access to Laundry (not everyone)
Done.

> o If this is possible, under “Browse > Laundry” keep the list view and remove the “List” and “Map” links in the header
Done.

> ⦿ Under specific Laundry locations:

> o Change the selected star to an orange star (not navy)
Done (everywhere we display a laundry room).

> o Delete the second instance of the word “Laundry” located on the white background (below the navy header that also reads “Laundry”)
Done.

> o Align favorite star with the location header. If possible, slightly decrease the laundry location header font size to accommodate star fitting to the right of it.
Done.

> ⦿ My Laundry screen:

> o Update default “Whoops” message to “Tap the [star] on laundry locations to quickly find them here.”
Done.

> o Once favorited laundry locations show up under “My Laundry,” add a “View All” link at the bottom of the “My Laundry” screen that leads to the complete laundry location list (Browse > Laundry)

Not done because this issue contradicts the common rule that we follow. Tapping on "View All" in any widget from the Favorites panel should perform the same action as tapping the corresponding entry in the Browse panel. Currently the entries from the "My" section in Browse panel that are linked to user favorites selection (e.g. My Events, My Dinings, My Campus Guide) open a list view with all selected (favorite) items, not the main home panel of the corresponding category.

I do not mind making any changes there but we should be at least consistent:
• do this for Browse / My / My Laundry as well;
• do the same for all entries from Browse / My section and corresponding widgets from the Favorites panel;

Please coordinate this with @pmarkhennessy.

**Comment by vburgett** [comment]
@mihail-varbanov the way all above requests are working now in 4.1.4 is correct. 
-Laundry was intended to be its own section under Browse like you have it.
-The last item was requested before we implemented the other "View All" instances so it is also correct as is in 4.1.4. 
@clint156 or @kpecknold please review as well and close the ticket if you agree that all is accurate now. Thank you!
