### ISSUE TITLE
[BUG] Redirect My Notifications favorites widget

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#1972]
When I tap on My Notifications under Browse, I expect to see the same screen I see when tapping the bell notification icon in the upper right hand corner of the app. 

**To Reproduce**
1. Go to Browse
2. Tap "My"
3. Tap "My Notifications"
4. See first screenshot

**Expected behavior**
1. Go to Browse
2. Tap "My'
3. Tap "My Notifications"
4. See second screenshot.

**Smartphone (please complete the following information):**
 - Device: Android
 - Version 4.0.49
 
**Screenshot #1**
![Screenshot_20220712-145121](https://user-images.githubusercontent.com/1044905/178583812-4338684e-0f8f-47b4-83db-3fbcacea5117.png)

**Screenshot #2**
![Screenshot_20220712-145137](https://user-images.githubusercontent.com/1044905/178583817-60cffb2d-1530-4d0e-8e48-b1e77c890102.png)

**Comment by mihail-varbanov** [comment]
@vburgett, we used to had an ability for mark notifications as favorite. They had been processed in similar manner as My Events, My Dining, My Campus Guide, etc. in Favorites and Browse panels.

The favorite button was removed for notifications by request in "2022-07-03-ILAppUpdates-VB.pdf" / Page 19 [https://github.com/rokwire/illinois-app/issues/1910].

We have inconsistency at the moment that I tried to explain in #2008.

We should either remove "My Notifications" widget from Favorites, link "My Notifications" from Browse to what the bell button does (that will remove the Favorite star of this entry like Academics / My Illini was before its removal) or remove this entry from Browse / My at all,

or bring back the initial logic that allowed marking notifications as favorite.

**Comment by vburgett** [comment]
The idea behind the bell icon was to centralize notifications there. I see the My Notifications favorite as unnecessary with the new bell icon located on all the main screens. 

I would vote for removing the "My Notifications" widget from Favorites and from Browse. Cc: @pmarkhennessy in case there is disagreement here. 

(In the future, the bell icon showing a red mark when new unseen notifications are present would help standardize this user experience to match other popular apps like Facebook and Instagram.)

**Comment by mihail-varbanov** [comment]
Hi @pmarkhennessy,

In general, we have two options:

A. Keep the Favorite Notifications Support
In this case all we need to do is to bring back the favorite (star) button in Notifications panel.

B. Remove the Favorite Notifications Support
We can do what @vburgett suggest: remove the "My Notifications" entry in Browse and the corresponding widget in Favorites.

Alternatively, we could keep "My Notifications" entry in Browse panel. It could open Notifications panel (as the bell icon above). It will be linked to a new "Notifications" widget in Favorites panel that contains the latest notifications horizontally scrollable (like My Groups, polls, whatever).

Please discuss this with JP if it is necessary and let me know what to do, because at the moment we are not quite consistent: we Favorite Notifications support with turned off capability to mark any notification as favorite.

**Comment by mihail-varbanov** [comment]
@vburgett, I believe everyone considers the lack of a red badge with unread notifications count on the bell icon. Unfortunately we are not capable to handle this right now because we do not have neither the relevant backend support nor the corresponding handling in the client. In short, this will not be a quick work.

**Comment by pmarkhennessy** [comment]
@vburgett let's defer for 4.1 or 4.2. There has been so much work in this release that we really need to breath then improve

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, please decide what exactly to do in 4.1. For reference: https://github.com/rokwire/illinois-app/issues/1972#issuecomment-1185237940

**Comment by vburgett** [comment]
Can we proceed with B. remove the "My Notifications" entry in Browse and the corresponding widget in Favorites?

**Comment by mihail-varbanov** [comment]
**Re: University Monday 2022/08/01** / 2022-08-01

_1.2 Was #1972 Remove the "My Notifications" widget from Favorites and Browse done?_
MV: No, still awaiting your decision. In short, this is the situation:

We used to have the ability to mark Inbox notifications as a favorite. There is a "My Notifications" entry in the Browse panel that displays the favorite notifications, similarly to favorite laundries, for example.

Vanessa wants to remove this and to leave the bell icon in the header bar as an only way to access notifications. In my opinion she did not understand what "My Notifications" entry from Browse actually does.

So, in my opinion we have a few options:

A) Remove everything related to notifications from Favorites & Browse panels leaving only the bell icon as a gateway (what Vanessa suggests).

B) My feeling is that the philosophy of UIUC 4 is different - offer as much as you can and let the user choose what to see and use. In this way of thoughts I would:

B.1. Keep "My Notifications" widget / browse entry allowing the user to mark Inbox notifications as favorite

B.2. Add a new "All Notifications" Favorites widget and Browse entry. The widget will display the most recent notifications horizontally scrollable (not only the marked as favorite). The Browse entry will do the same as the bell icon on top. The benefit of this addition is the ability to have the most recent notifications available in the Favorites panel.

I think that point B is the standard approach in the UIUC 4 as we have All/My Groups, All/My Events, All/My Dinings, and so on. BTW, FYI, Wellness Resources also does not follow this model quite strictly.

**Re: University Monday 2022/08/01** / 2022-08-02

_2.1 On "#1972 Remove the "My Notifications" widget from Favorites and Browse", please do option B._

**Comment by mihail-varbanov** [comment]
In version 4.1.8:

1. A new Favorites widget is created for Favorites panel content. It is called "Recent Notifications" and displays the most recent notifications in a horizontal page view, followed by "View All" link at the bottom.

2. A new section in the Browse panel is created. It is called "Notifications" and contains two entries inside: "Recent Notifications" and "My Notifications"."Recent Notification" does the same as bell icon, marking it as favorite adds the "Recent Notifications" widget in Favorites panel. "My Notifications" (that also persist in "My" section) opens a panel with notifications marked as favorite, 
3. The description of this new section is dummy (lorem ipsum) and needs to be updated. Let me know please if they (Vanessa) want some better wording (e.g. "All Notifications" instead of "Recent Notifications").

**Comment by vburgett** [comment]
When a user taps on a "recent notification" in the new favorites widget in 4.1.14, it leads to a new screen that has the loading circle spinning with no content ever loading. What should a user see?

I'm sorry I can't help with text for Notifications under Browse. I see Notifications as a utility represented by the bell icon. I can not imagine a time when a user would value favoriting a notification so I am not sure how to describe what notifications does as an "app section" that can be favorited.

**Comment by vburgett** [comment]
I'm marking this as a high priority since the app should not be released with placeholder text.

**Comment by mihail-varbanov** [comment]
1. The problem with the "new screen that has the loading circle spinning with no content ever loading" has nothing to do with My Notifications widget. It also persists when you tap on a Group notification card from Notifications panel. I created a separate issue for this (#2223) and fixed it in 4.1.16.

2. I am not the right person to provide UX description in English but since no one else will do it, I will. The Lorem Epsom placeholder is replaced by "Shortcuts to your in-app notifications from groups, academics or athletics events and more." in version 4.1.16.
