### ISSUE TITLE
[BUG] "Star" icon to favorite Notification is missing

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2022]
**Describe the bug**
There is no "Star" icon to favorite the Notification favorite.

**To Reproduce**
1. Install the Illinois app
2. Complete onboarding and log in as a university student
3. Navigate to Notification

**Actual result**
On the "Notification" screen, there is no "Star" icon to favorite the notification.

**Expected behavior**
The "Star" icon should be available to the user to favorite the notification

**Screenshots**
![Favourite Notofication](https://user-images.githubusercontent.com/26231179/179310209-81811446-8230-4ab6-896f-a44d6d555d62.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 4.0.53]

**Comment by vburgett** [comment]
@Priyaravi8 we just had the star removed from each notification since these updates don't lead to a tool or additional functionality/information, and there was no identified value for a user to want to favorite a singular update within a stream of notifications. Notifications is a central place for a user to be pinged from various sections within the app (courses, groups, etc.).  Please let me know your point of view if it differs. If not, please close the ticket. Thank you!

**Comment by vburgett** [comment]
I see the issue now. Please update the default Favorite widget text for Notifications to "See your most recent <Notifications> for quick access here."
![Screenshot_20220717-122237](https://user-images.githubusercontent.com/1044905/179417570-fbf53ff0-b87d-4042-91c8-634bdb106705.png)

**Comment by dobromirdobrev** [comment]
The text is changed as desired by @vburgett . Fixed in version 4.0.55

**Comment by Priyaravi8** [comment]
This issue is resolved
