### ISSUE TITLE
[BUG] Polls - vote is recorded before "done voting", repeat votes doesn't allow change

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2138]
**A. Poll vote gets recorded immediately on tap, doesn't wait for user to tap "Done Voting"**
**To Reproduce**
1. Create a poll 
2. Start the poll
3. Tap Vote
4. Select an answer
5. See Vote counted and closed, no option to select change answer and indicate "Done Voting"

**B. When a poll is set to "allow repeat votes", it doesn't allow the voter to select an option different from the first one they chose.** 
**To Reproduce**
1. Create a poll and set it to "allow repeat votes"
2. Start the poll
3. Tap Vote
4. tap Done Voting
5. Tap Vote
6. Note you can't choose any option other than the first one. ALSO it records the vote with each tap - before you tap Done Voting

**Expected behavior**
A) a vote should not be recorded before tapping "Done Voting" - in case the user changes their mind or makes a mistake
B) user should be able to select a different option if the poll allows repeat votes

Android - Google Pixel 2
Illinois App version 4.1.4

**Comment by dobromirdobrev** [comment]
Hi @kpecknold ,
These problems that you described are not issues but an intentional behaviour. 

Regarding **A**: The app intentionally hides the poll prompt after user selects a vote for "single vote" polls.
Here is the requirement from 2022/05/09:

> 2.5 If a Poll is a single vote poll then when a user votes close the panel, do not show the 2nd panel with the "Done Voting" button. We only want to see the 2nd panel for multi voting.

Regarding **B**: This is expected. If you want to create poll that allows a user to repeat votes and to select different options, on creating the poll you will have to select both "Allow selecting more than one choice" and "Allow repeat votes".

cc @pmarkhennessy

**Comment by kpecknold** [comment]
repeat voting has been disabled, solving this issue.
