### ISSUE TITLE
[BUG] Illini Cash - login should not be required to add Illini Cash

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2175]
**Describe the bug**
Illini Cash can now only be accessed via the wallet, and requires a login.
It should not be necessary to be logged in to add Illini Cash - only to view a balance.
Parents/families frequently add Illini Cash for their students. 
When we had the Illini Cash tile, it didn't require a login to add, so this is an unintended consequence of the redesign.

There is a design implication @vburgett 

**To Reproduce**
1. Sign out
2. tap on the Illini Cash under wallet or in your favorites
3. See message requiring login

**Expected behavior**
Anyone should be able to add Illini Cash to an account if they know the person's UIN.

**Comment by vburgett** [comment]
Could we add a "Gift Illini Cash" section in the Wallet that mirrors the "Add Illini Cash" option but 1) doesn't require a netid login and 2) isn't pre-populated with user data?

**Comment by mihail-varbanov** [comment]
What I did in 4.0.16 was:

1. Keep the "+" (Add Illini Cash) button in Wallet / IlliniCash card in Favorites panel available (visible) when the user is not logged in.

2. Added "Add Illini Cash" entry in Wallet section in Browse that opens Add Illini Cash panel nevertheless the user login status.

2.1. This entry is not linked to any component from Favorites panel so it has no favorite star button.

2.2. I used "Add Illini Cash" instead of "Gift Illini Cash" because this was the wording that we used so far (that the users should be familiar with) and because this is the wording that we use in all other places across the app (the title of the panel that does this and the button from IlliniCash panel that also opens it). So if we want to replace this with "Gift Illini Cash" anyway, we should do this separately and consistently everywhere across the all app components.
