### ISSUE TITLE
[FEATURE] Please add link to Video Tutorials in Campus Guide.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2176]
[[ @vburgett  - Would you please review this and assign it to Mark when it's OK? (thanks, joe) ]]

So that we can make new videos available within the app as they are created, we would like to add new videos via Campus Guide.

Please confirm with JP, but he asked to have a landing page for Video Tutorials in Campus Guide that could be linked from Browse > App Help.

_Browse > App Help > Video Tutorial_ 

can point to 

_Campus Guide :: Help > Video Tutorials > Video Tutorials for the Illinois App_

Make Video Tutorial plural in the menu item name.

**Comment by vburgett** [comment]
100% in agreement with this plan. Thank you, @joegrohens!

**Comment by pmarkhennessy** [comment]
@joegrohens for new videos you have to store them in YouTube for example or ask operations to store them in AWS somewhere. Either way all you need is the URL to them. I am not sure why you need my involvement?

**Comment by joegrohens** [comment]
@pmarkhennessy 

Your part is to connect the top-level menu in the UI to the page in Campus Guide.

**Comment by mihail-varbanov** [comment]
@joegrohens,

We can easily redirect Browse: App Help / Video Tutorials to open specific Campus Guide page. However the problem is somewhere else:

I just looked at the "Video Tutorials" page definition. Setting a [youtube page URL](https://youtu.be/8K7X36mIbf0) as an image will not cause the app to play the video from that youtube page. The app expects image and only image URL at this place and setting a URL with any other content type there is wrong.

Currently the campus guide engine in the Illinois app is not capable to display video content inside a Campus Guide detail panel. Implementing such feature is not quick and easy and I do not think this is achievable for the upcoming 4.1 release.
