### ISSUE TITLE
[BUG] Illinois app displays 'Location access denied' message 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#223]
**Describe the bug**
Illinois app didn't provide an option to grant the location access to the user. It displays - "You have already denied access to this app".

**To Reproduce**
1. Install the Illinois app
2. Proceed to complete the onboarding steps
3. Tap on the Share my location button on the screen "Know what's nearby"

**Actual Result**
Illinois app didn't provide an option to grant the location access to the user. It displays - "You have already denied access to this app".

**Expected behavior**
If the location is not turned on for the App while installing, App should provide an option to grant the location access to the user. 

**Screenshots**
![location access](https://user-images.githubusercontent.com/26231179/106510626-cd770980-6494-11eb-8f13-eccbc38cfb64.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.4]

**Comment by mihail-varbanov** [comment]
We are able to request permission only if this permission is not already requested or set. If it is already determined (nevertheless allowed or denied) any consequent permission requests have no effect, they are simply ignored by the operating system. The reason for this behavior of the operating system is obvious - not to allow an application to bother the user with permissions access requests multiple times. That's why it is better to state that the permission is already granted or denied, instead of making another request that will be ignored. I do not think we should change the current behavior, we could only think about some more appropriate user message in case the permission is already denied.
