### ISSUE TITLE
[BUG] iOS - App is crashing while browsing

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#229]
**Describe the bug**
Illinois app is crashing while browsing around the screen

**To Reproduce**
1. Install the app
2. Complete the onboarding screen
3. Select a university student as a role
4. Proceed without verifying his phone number
5. Tap on the Browse menu

**Actual result**
Illinois app is crashing

**Expected behavior**
The app should work fine without crashing

**Smartphone (please complete the following information):**

 - Version [e.g. 2.4.0]

**Comment by mihail-varbanov** [comment]
I was not able to reproduce this problem either
https://user-images.githubusercontent.com/5631487/107054123-64ff9380-67d8-11eb-8c5b-777ed9292305.mov

**Comment by mihail-varbanov** [comment]
I made a fresh release build from the current develop branch that points to production. Again, I failed to recreate this problem. I was not able to recreate it in debug builds either (what I need for locating the reason). I emulated tallent chooser service requests failures but in this case we switch to local content builds so I was not able to recreate the problem. I just found a suspicious assignment in application code that could create a problem rather theoretically, and I fixed it. As a general I do not see what else I could do in this situation. Тhe only thing I can suggest is to test again on a build from the current develop branch (version 2.4.2 and above).

**Comment by mihail-varbanov** [comment]
I just got access to TestFlight builds and recreated the problem with the TestFlight version. It seems we do not make a request to FlexUI / Tallent Chooser because there is no spinning cursor at all on the Continue button from the Roles panel. However there is not much to do on this TestFlight build. I made debug & release builds from release/v2.4.0+500 branch (that should have been used for the Test Flight build) but I am still unable to recreate this problem. I will try to hunt the TestFlight version with Charles proxy tomorrow and see what network activity is actually performed.
