### ISSUE TITLE
[BUG] Black screen results at the end of onboarding

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2395]
**Describe the bug**
Black screen results at the end of onboarding.

**To Reproduce**
1.Install the Illinois app
2. Continue with initial onboarding.
3. . Select University student as a role and login with netid/pwd

**Actual Result**
Black screen results at the end of onboarding

**Expected behavior**
App should log in successfully without a black screen

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.1.31]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 If you then run the App again it is OK? Meaning this only happens after an install?

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,
I cannot reproduce this issue. I tried with various builds, user scenarios, Android OS versions - all work as expected to me.

I tried to apply a fix on blind without knowing if this changes it or not. Please test with version 4.1.32 and let us know if the issue is resolved. If it is still not - could you please take a short video and give us as much details as possible?
Thanks cc @pmarkhennessy

**Comment by Priyaravi8** [comment]
> @Priyaravi8 If you then run the App again it is OK? Meaning this only happens after an install?

@pmarkhennessy  - Yes, the black screen appears when the user installs the app and goes through the login process. Once I close and reopen the app, it works fine. 
To reproduce this issue, Uninstall the app and clear the cache. Install the new version and proceed with the login process.

**Comment by Priyaravi8** [comment]
This issue is fixed in version 4.1.34
