### ISSUE TITLE
[BUG] Member list in groups repeats members multiple times

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2413]
**Describe the bug**
The list of members in a group shows each member multiple times. 

In the Gus group, for example, owned by Vanessa, there are said to be 26 members. Each member is shown 13 times or more.

When I view "All," I am included in the list of members multiple times. When I view "Members", I am shown only once. But all others except the admin seem to be shown many times. (I didn't analyze quantitatively)

**To Reproduce**
1. Open a group that you are a member in. 
2. Tap the link to view members.
3. Try selecting different filters - All, Admin, Member to see different effects.

**Expected behavior**
Each member should be shown only once.

**Equipment**

iphone 11 - running testflight, Illinois app v4.1.34

**Comment by joegrohens** [comment]
Possibly related to #2406

**Comment by joegrohens** [comment]
This is still a problem.

![Screenshot 2022-09-29 at 7 08 11 PM](https://user-images.githubusercontent.com/66988329/193165482-d9c1dc5e-3692-4839-8d25-79a0a8394828.jpeg)

**Comment by joegrohens** [comment]
This is still a problem in v4.1.36

**Comment by joegrohens** [comment]
Kathryn asked to see an example of this problem.

Below is a link to video screen recording of the Groups Feedback member roster. A segment of the roster (about eight people) repeats more than 30 times. A few other people repeat as well, but not as consistently. Some members do not repeat at all. I don't know if there is a clear reason for it.

https://drive.google.com/file/d/1G0RUsYHo34rcQWIsKlSNVMRbGUlVydk3/view?usp=sharing

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,
I'm unable to reproduce this problem with the groups that I'm a member/admin. That's why I requested to join to the groups "Gus", "Rokwire Interest Group" and "Groups Feedback". 

To the moment that I write this message, I became a member of "Groups Feedback". I cannot recreate the problem observed in the video and screenshots.
My tests were with version 4.1.26 for Android.

I'll wait to become a member to the other groups and will try with them. Meanwhile if you notice any other details that will be helpful, please share them with us. cc @pmarkhennessy

**Comment by pmarkhennessy** [comment]
@mihail-varbanov you should take a look at this as it's an iOS issue. If you scroll very slowly, when you get to the end of the list it then starts duplicating. So if it has 13, the repeats start after 13.

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, it is not an iOS issue, it is Flutter issue. Fixed in 4.2.3.

**Comment by joegrohens** [comment]
This appears to be fixed. (Currently testing v4.2.42)
