### ISSUE TITLE
Groups member search focus not given to text input[BUG] 

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2494]
**Describe the bug**

**To Reproduce**
Go into a group membership list and click the magnifying glass in the upper right 
Currently no cursor is displayed and there is no feedback indicating that the white bar is in fact a text input.
**Expected behavior**
 Focus should be given to the input field and the cursor should be visible. The lack of feedback when clicking on the magnifying glass is somewhat confusing. If it operated like the magnifying glass searching groups it might be more clear. On that screen, the white bar with the "X" and the magnifying glass isn't visible until the user clicks on the magnifying glass for the first time. 

**Smartphone (please complete the following information):**
 - Device: Samsung a53
 - OS: Android 13
 - Version 4.1211

**Additional context**

**Comment by pmarkhennessy** [comment]
@clint156 OK. We will start to work issues towards the end of November

**Comment by TodorBachvarov** [comment]
This was improved some time ago. The input field is not focused by default otherwise the visible part of the screen is too small. The improved part is when we click the magnifying if will focus the input field (and show the keyboard) and also the "x" button will remove the focus and will hide the keyboard. This provides the described feedback for the search and close button. @clint156 please let me know if some additional fix is required.

**Comment by clint156** [comment]
Verified fixed in 4.2.47. The search input field, "X" and search icons are visible when going into the group membership list. Focus is not there. By either clicking the search icon or by clicking into the search field focus is given and the cursor is visible.
