### ISSUE TITLE
[BUG] Error message in map is not user friendly

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2615]
**Describe the bug**
Error message displayed for the map is not user-friendly. 

**To Reproduce**
1. Install the new Illinois app
2. Navigate to Map and tap on the direction
3. Tap on Bus for the direction

**Actual message**
A development code error message is displayed to the user

**Expected behavior**
Error messages displayed should be user friendly

**Screenshots**

![Bus route](https://user-images.githubusercontent.com/26231179/205164960-0e40d7ab-a8de-4023-928f-6008765ff01d.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.2.31]

**Comment by pmarkhennessy** [comment]
@mihail-varbanov This may be due to noise with MTD, but figured while you are working here...

**Comment by mihail-varbanov** [comment]
I added human readable description of the problem (e.g. "Failed to find a route") but I still keep the error description (e.g. "ZERO_RESULTS: null") that comes from Google Directions services because it brings additional info about the exact reason for the failure. This will get available in the 4.2.36 build.
