### ISSUE TITLE
[FEATURE] Standardize logged out widget

### ISSUE THREAD

**Issue by roberlander2** [rokwire/illinois-app#2668]
**Is your feature request related to a problem? Please describe.**
There is no standard widget to show a certain privacy level or login type is required to access a given feature of the app.

**Describe the solution you'd like**
Create a widget that can be shown to users when they are logged out or their privacy level is too low, not allowing access to a given feature of the app. The widget should accept arguments such as minimum privacy level and any required login type, and it should have action buttons that open the relevant content in Settings or Profile to be able to login or update privacy level.

**Describe alternatives you've considered**
A standard widget is unnecessary, but it will be helpful in keeping styling consistent and cut down on code duplication on each panel that needs to use similar functionality.

**Comment by vburgett** [comment]
@roberlander2 to add to your idea, this Favorites widget would be a "Profile" dashboard. Let me know when our Design team can assist. Thank you!

**Comment by joegrohens** [comment]
@roberlander2  - Related to the question of having a standard "widget". 

I'm not sure how you mean "widget", but ...  the most common display of privacy level error messages appears in a modal dialog like the one below. I don't know how you refer to this screen internally.

![wallet privacy level 3 copy](https://user-images.githubusercontent.com/66988329/207430071-43de506b-100f-4a8f-87f1-bb6d994f0090.JPG)

Many of the json strings for the Wallet are displayed in the same screen.

(See strings.english.json panel.browse.label.logged_out.illini_cash": "You need to be signed in with your NetID to access Illini Cash. Set your privacy level to 4 or 5 in your Profile. Then find the sign-in prompt under Settings.") 

You may know all this.

....
I would like to add that we try to use "sign in" rather than "log in" throughout the app. (JP's preference, and for consistency.)

**Comment by roberlander2** [comment]
Thanks @vburgett, @joegrohens,

I use the term "widget" just because that is the name of Flutter UI elements. Yes, I have seen the existing privacy error dialogs as you show above. The goal of this new widget is similar to the existing dialogs, but it includes buttons that quickly open the appropriate pages ("Profile", "Settings") and it will allow privacy level, sign in type, and user role requirements to be updated without requiring code changes. Please let me know if you have any additional comments or questions.
![Screenshot_20221213_164408_Illinois 1](https://user-images.githubusercontent.com/46940735/207461077-69a5ec3c-b82b-4a52-b2c8-5d339710bf10.jpg)
![Screenshot_20221213_164422_Illinois 1](https://user-images.githubusercontent.com/46940735/207461149-20a98848-eb0d-4319-aa39-776d5813a303.jpg)

**Comment by joegrohens** [comment]
@roberlander2 @vburgett 

Robert - 

Your idea for the standardized "not signed in" widget is great.

Ideally, these dialogs will also educate users about how privacy level and sign-in are related.

I'd like to suggest giving a more user-friendly (less negative) error message for "You may not access <feature>"

Options:

- You need to be signed in with your NetID to access <feature> [long, but informative]
- Sign-in with your NetID to access <feature> [still makes it clear that you need NetID]
- Sign-in to access <feature> [terse, but not negative in mood - they can infer the NetID part from displayed procedure.]

I'm fine with any of those options.

.....
Additionally, I would not number instructions when there is only one step.

Joe

**Comment by roberlander2** [comment]
Thanks @joegrohens,
I included your suggestions in my changes (used the third option you suggested for the error message title). I believe these changes will make it into a new build soon for testing, so please let me know if you have any more suggestions.

Ryan
