### ISSUE TITLE
[BUG] When new group is created, sort it to the top of the list

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2683]
**Describe the bug**
In general, groups are sorted by most recent. However, when you first create a group, it goes to the bottom of the list. Please refresh the view and sort it to the top.

**To Reproduce**
1. Create a group
2. See that it is at the bottom of the list of groups until you go out and back in

**Comment by mihail-varbanov** [comment]
Hi @kpecknold,

> In general, groups are sorted by most recent.

This is not true. The groups are sorted by category and title, both in All and My Groups lists. 

> However, when you first create a group, it goes to the bottom of the list. 

It does not go to the bottom of the list, it goes in the place where the above sort order has determined.

> Please refresh the view and sort it to the top.

Тhese are mutually exclusive requests. "Refresh the view" means to insert the new group at the place determined by its category and title, "sort it to the top" defines another place to show the new group.

It would be some ugly patch to force a newly created group to appear at the top of the list of groups that are sorted alphabetically by category and title. This would be confusing for the user as well (in my opinion) because if the user refreshes the view the newly created group will disappear from the top position.

What we can do is:

1. To change the general sort order for groups, e.g. by create/update times. The recently updated groups will appear on top of the list, as well as the newly created ones. We do not remember for sure why we sort the groups in the current way (alphabetically by category & title) but our feeling was that this was issued by the University. So if we change the sort order of the groups we can fulfill this issue.

2. Another option, in case we do not want to change the global sort order, is to scroll the view to the newly created group so that to ensure its visibility. Or alternatively, when a group is created to automatically open its detail panel because this is what most probably the user would do after locating the group?

@kpecknold, let me know please which way we should take. Adding @mdryankov to this thread as he maintains the groups sort order on the backend side.

**Comment by mihail-varbanov** [comment]
Update:

I just found a bug in the application that affects groups sort order. If My Groups favorite widget is visible it might affect the order of my groups in the Groups Home panel. This widget sorts the groups by their update time and Groups Home could arbitrarily display these groups sorted as in the Favorites widget or sorted as they come from the backend (alphabetically by category and title). I have fixed this now for version 4.2.39 [#2716].

This might be the reason for the confusion about the sort order in the Groups Home panel. However, the question for the groups sort order in home panel is still actual - which sort order is more useful and convenient - by update time (like in All/My Groups) or by category & title.

**Comment by kpecknold** [comment]
@mihail-varbanov  The team just discussed and would like for groups to be sorted alphabetically by title only (don't use category). Please make this true for all groups lists (favorites, my groups, all groups...)

**Comment by mihail-varbanov** [comment]
@kpecknold, @mdryankov handled this in Groups BB, currently on Dev only.

I think we should preserve the most recently updated order in horizontally scrollable All/My Groups widgets in Favorites panel because this makes sense, I believe.

Regarding to locating a newly created groups, we do not put it on top of the list but scroll it down to make this group visible.

**Comment by kpecknold** [comment]
@mihail-varbanov   Yes, I agree, preserving the "most recent" sort for the horizontal scroll in Favorites makes sense. Thank you for updating the sort to alphabetical in the list view.
