### ISSUE TITLE
[BUG] Refresh Maps view when you navigate back to it

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2734]
Right now, new MyMcKinley appointments don't show up on the map, unless you change the drop down choice to something else and back again. 

**To Reproduce**
1. Have an exisiting McKinley appt
2. Go to maps
3. Choose MyMcKinley appts 
4. See the pin with the appt
5. Schedule another appt
6. Wait for it to show up under Wellness, MyMcKinley Appts
7. Go back to maps
8. See that the new appt does not appear on the map

**Expected behavior**
Each time I navigate to maps, the current selection should refresh

**Comment by mihail-varbanov** [comment]
This is fixed in 4.2.43.

> Each time I navigate to maps, the current selection should refresh
This is quire strong requirement as dining locations, laundries, buildings or MTD stops are supposed to change quite rarely. So we refresh appointments on tab change but not for the other display types. We also refresh the content when being awaken from background if we resided there for more than given period of time (refreshTimeout defined in app config). I believe these loosen conditions for refreshing map content would resolve the problem.

**Comment by kpecknold** [comment]
@dr-mel   Can you please re-test this?  I don't have a McKinley appt to be able to simulate. And I'm sorry, I can't join the testing event.

**Comment by kpecknold** [comment]
Confirmed fixed in 4.2.47
