### ISSUE TITLE
[USABILITY] Various issues with Favorites Widget for Campus Safety Resources

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2758]
The Favorites Widget being developed for Campus Safety Resources has a few usability problems.

I realize that this widget is in development. And I have seen it changing hour by hour. 

However, given the release timeframe, I thought I'd better list the issues no matter how obvious or short-lived they may be.

This report is based on Android Dev build v4.2.40

**Problems**

1. There are two favorites widgets with different functionality. There should just be one.
2. The pre-populated Campus Safety Resources faves widget 1 contains ALL items from the list. And they can't be removed. That's probably too many to be truly useful on the Favorites page.
3. The unpopulated Campus Safety Resources faves widget 1 allows adding and removing items. This is the widget to use. It should be pre-populated with the following defaults, preferably in this order (SafeRide, SafeWalk, Illini Alerts).
4. The My Campus Guide favorites widget -- at one time -- was duplicating items that were favorited in the Campus Safety Resources faves widget 2. This seems to be fixed now, and faves from Campus Safety Resources do not appear on My Campus Guide. That is good, in my opinion.

I think if the Favorites Widget for Campus Safety Resources does not have all of the issues above fixed, it would be best to release the app without that Favorites Widget.

Joe

**Comment by mihail-varbanov** [comment]
Hi @joegrohens,

We have two different Favorites widgets for "Campus Safety Resources" and "Campus Guide Highlights". They used to use the same title "Campus Safety Resources" which brings confusion. This was introduced when we renamed the ex "Campus Safety Resources" to "Campus Guide Highlights" and then introduced a new "Campus Safety Resources" browse entry and widget. This is now fixed.

We have a "Campus Safety Resources" Favorites widget that displays favorite items from "Campus Safety Resources" Guide section.

"Campus Guide Highlights" favs widget used to display the entire Campus Guide Highlights content (that is the promoted list in Campus Guide), nevertheless if some item is selected as favorite or not. In short, it duplicates the list content that we see when we navigate to Browse / Campus Guide / Campus Highlights.

I fixed the "Campus Guide Highlights" widget title and content stings inside.

I also made it to behave similarly to "Campus Safety Resources" widget:
- to display only favorite items;
- items, marked as favorite from Campus Highlights panel, to appear only in Campus Highlights widget and not in "My Campus Guide"

Let me know please if this is the expected behavior of "Campus Guide Highlights" favs widget.

**Comment by joegrohens** [comment]
@mihail-varbanov 

I have tested the favorites widget. It works as expected. Thank you.
