### ISSUE TITLE
[USABILITY]Onboarding Location screen - Device Location access information is not displayed

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#277]
Describe the usability issue
On onboarding steps, the "Enable location specific services" screen doesn't display the pop up  "Allow Illinois access this device's location" 

To Reproduce

Install the Illinois app
Proceed with onboarding steps

**Actual result**
On onboarding steps, the "Enable location specific services" screen doesn't display the pop-up "Allow Illinois access this device's location" As it displayed on the Explore screen with Events.

Expected behavior
The user would be expecting this information on the boarding screen but not on Explore screen.

Screenshots
![location pop](https://user-images.githubusercontent.com/26231179/121205977-b4fd6e00-c83d-11eb-89a8-1bf28690dbfa.png)

Smartphone (please complete the following information):

Device: [e.g. iPhone and Android]
App version - 2.4.16

Additional context

**Comment by isaac-galvan** [comment]
Hi @Priyaravi8 per platform policies, we need to ask for permission to use location only at the time we are going to provide location-based services, and not before. Since we don't use location at any time during onboarding, we don't display the system location permissions at that time. When a user goes to see events, they are offered to filter by "Events Near Me", and thus shown the request at that time.  This is a change from how we've done it previously, but it is necessary. Thanks!
