### ISSUE TITLE
[BUG] Notifications: muted and unread not working

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2778]
I see the same Group post notification from today in Unread, Muted, and All Notifications in a Group I am the admin of (Would You Rather . . .), and I have the "posts" notification set to "off" at the group-level. I would expect to see this post only under Muted. 
(If we run out of time, could we just release without Muted Notifications?) 

I also see notifications I have clicked thru on multiple times still showing up under Unread Notifications. This may be related to #2643. 

V4.2.42

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
This issue is a result of problems in the UIUC app and in the backend. The problems in UIUC app are fixed in version 4.2.43 and the backend problem is being worked on https://github.com/rokwire/notifications-building-block/issues/126 .
So, when we have it done, we will let you know to re-test this issue and verify if it is fixed.

Also, please note that the above is related to #2643 and both should get resolved. cc @pmarkhennessy
