### ISSUE TITLE
[BUG] local group notification settings do not override global settings that are set to OFF

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2840]
**Describe the bug**

With Global GROUP notifications set to OFF, you cannot override the setting in a Group. But it looks like you can.

**To Reproduce**
1. Go to Notifications > My Notification Preferences
2. Set Group Posts to OFF
3. Go to Notification Preferences in a Group 
4. Set Post Notifications to ON
5. Create a Post.
6. Look for a Notification of the Post (e.g., in Muted Inbox)

Result: No Notification is delivered anywhere.

**Expected behavior**
The UI makes it look like you can override the global setting and enable notifications for Posts. 

Either (1) dim out the option to re-enable the notification, or (2) actually override the global setting of OFF.

**Screenshots**
![Screenshot 2022-12-21 at 10 35 51 AM](https://user-images.githubusercontent.com/66988329/208957406-e00f28dc-ffab-46ce-94f5-87c0584a9f0a.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
- apk v4.2.45 (dev)

**Comment by mdryankov** [comment]
Hi @joegrohens, 

I will try to explain the current logic skipping the tech part. The current design omits the recipient if the global setting is off. This means that the message will not be linked to a specific recipient if his/her global setting is off and this message will not appear within the Inbox and additionally no push notification would be sent to the exact user. 

We have to options:
1. Keep as it is. The message will not be associated for the user if the the global setting is off (e.g the message will not appear in the Inbox)
2. Create the message for the exact recipient but change the Mute flag = true. In this case the recipient will receive the message in her/his inbox except the push notification (no push notification). 

Please confirm. 

NB: The (group) local & global settings are controlled on two independant places, no matter they have a common effect - the message will be muted or not! Please keep that in mind when you introducing feature requests for the related logic, because it's quitely complicated. 

CC @pmarkhennessy  @petyos

**Comment by joegrohens** [comment]
@mdryankov @pmarkhennessy @petyos 

Thank you for the helpful explanation of the Notification settings method. 

I am not in a position to recommend which of your two options is best.

I do think that if you go with option 1 (keep as is), then, for good user experience, the ability to re-enable the notification locally should be dimmed, so that users don't try a setting that can't work.

**Comment by mdryankov** [comment]
@joegrohens, seems I saw your last comment too late and my intention from @pmarkhennessy  was to apply option 2. 
Now Option 2 has been implemented and deployed on dev. 

Please go ahead and test. I'm not sure who is the decision maker. We could leave the new state or revert my changes. I will wait an explicit confirmation how to proceed further.

**Comment by joegrohens** [comment]
@mdryankov Thank you. We should test it with the change you committed and get feedback.

**Comment by vburgett** [comment]
Thank you, @joegrohens and @mdryankov, for working on this update. 

I would expect option 2 as the behavior with those specific Group notifications showing up under All Notifications even when Muted is set to hidden. Does that match what was implemented? I am not sure what results from "Mute flag = true."

_Option 2: When a user turns "on" a local Group setting that is set to "off" in the global notification settings, a notification message will be created for that specific recipient but the Mute flag will change to "true." In this case the recipient will receive the message in her/his inbox but there will not be any push notifications (no push notifications)._

**Comment by joegrohens** [comment]
@vburgett and I tested this together today.

The local group notification settings properly override global settings.

Closing this ticket.
