### ISSUE TITLE
[BUG]  Privacy level 3 - Favorite screen - Add a text in Illini cash and Meal plan section

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2867]
**Describe the bug**
Favorite screen - User with Privacy level 3, Illini cash and Meal plan section is blank. The user should be notified with the text "You need to be logged in to access"

**To Reproduce**

1. Install the Illinois app
2. Set the privacy level to 3
3. Navigate to your Favorite screen and locate the Illini cash and Meal plan section.

**Actual Result**
Illini cash and Meal plan sections are blank.

**Expected behavior**
The User should be notified with the text "You need to be logged in to access"

**Smartphone (please complete the following information):**
Phone - iOS
App Version - 4.2.27

**Comment by mihail-varbanov** [comment]
Fixed in version 4.2.48.

**Comment by knguyenjahiel** [comment]
@Priyaravi8, @mihail-varbanov: I've verified the notice of the required level 4 or 5 sign-in is displaying for Illini Cash, Buss Pass, Illini ID, and Meal Plan. Please note that "Add Illini Cash" does not have this notice - this makes sense since parents/anyone can add $$ to a UofI affiliated individual.
