### ISSUE TITLE
[USABILITY] The Game Day Favorites Widget has no star

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2930]
v4.2.47

The GameDay Widget does not have a star. This is unlike other widgets in the Favorites screen. 

If I tap the star in the "Wallet" faves widget, it will remove the widget. If I want to remove the "It's Game Day widget", I can't do it from the Favorites screen itself. I have to remove it via Customize. 

@vburgett says that this widget should have a star.

Joe

**Comment by mihail-varbanov** [comment]
Fixed in version 4.3.25 *

* Please note that the GameDay favorite widget can add more than one particular game widgets. As they do not imply well into the standard compound favorite widget (heading & horizontal page scroll), each of the game widgets has a favorite star that turns off the entire (compound) GameDay widget.

**Comment by joegrohens** [comment]
confirmed fixed
