### ISSUE TITLE
[USABILITY] Names of destination buildings not displaying in ver.4.2.52 (they displayed in ver. 4.2.47)

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2996]
Describe the usability issue
The names of destination buildings are not displaying in ver.4.2.52 as they did in ver.4.2.47. Names of the surrounding buildings are displaying, however. Having the destination building names display will help users verify they have arrived at the right location for their events and courses.

To Reproduce
1. Events -> Suggested Events --> Single-day events
2. Select "Academic" for "Categories"
3. Find and touch event: Inorganic Faculty Candidate Majed Fataftah, Yale, "Electron localization and metal-metal bonding in biomimetic clusters" (I) to get event details.
4. Touch location of event: 1.7 mi away, CLSL B102
5. Follow map directions to destination

Current map display of destination (ver.4.2.52)
![DestinationBuildingName_Missing_4 2 52](https://user-images.githubusercontent.com/118769169/219790525-e9a694da-15d0-4fc6-85b9-85ca32d52477.png)

Expected behavior
I'd like to see the name of the destination building (similar to image below of ver.4.2.47)
![DestinationBuildingName_Displayed_4 2 47](https://user-images.githubusercontent.com/118769169/219790660-8b2b975c-bad5-40b7-9e4f-c2bc15f092b8.png)

Smartphone (please complete the following information):

Device: Android
Ver: 4.2.52

**Comment by mihail-varbanov** [comment]
Hi @knguyenjahiel,

I was not able to find the exact event mentioned in the description but I tried different events and I was unable to recreate this problem.

We do not prevent GoogleMaps to show building labels while navigating. We do this purposefully only in Map/Buildings when the camera is zoomed in enough (zoom level 17 or more).

We have not changed anything related to Google Maps since version 4.2.47.

I suppose you noticed that Google Maps has its own criteria whether and when to show building labels, that depends on current camera position and zoom. If you center a building inside the screen and zoom in the camera enough, can't you still see the building labels?

**Comment by knguyenjahiel** [comment]
It might have been a GoogleMaps thing. The event I used in my example was scheduled for just 1 day, and no longer active. I've tested other events and the building names are displaying properly. I will close out this item. Thank you!
