### ISSUE TITLE
[BUG] Group members are not displayed in Quick poll screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2998]
**Describe the bug**
Members of the group are not displayed on Create a quick poll in the "To" field

**To Reproduce**
1. Install the Illinois app
2. Navigate to Groups
3. Tap on Create Poll 
4. Enter the required field in Create a quick poll screen and Tap on the "TO" field to select the members

Actual Result
Only Admin is displayed in the drop-down list but not the members

**Expected behavior**
All the members should display in the list along with the Admin

**Screenshots**

![Quick poll](https://user-images.githubusercontent.com/26231179/219807736-d1e03438-19cb-46dd-8b7f-6b5aeec3e8c6.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version-4.2.52

**Additional context**

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,
These are not only admins (the name "Priya Ravi" in the drop down) but in this portion of the drop down are listed recently used members that you previously selected.

On first start the app will show only "All members" and "Select Members" items. When you choose "Select members" then a new panel will show with all available members and admins for the specified group. Let's say that you select a member "Bill Doe" from that panel. After that, this member will appear in the drop down so that you previously selected him. 

This behaviour was required some time ago in [#1450](https://github.com/rokwire/illinois-app/issues/1450) so it is expected.

As a conclusion, this is not a bug but a required feature.
