### ISSUE TITLE
[BUG] Building Names are not displaying in Maps >> Campus Buildings & My Destinations

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3099]
**Describe the bug**
Many building names (such as Follinger Hall, English Building, Henry Administration) are not displaying in Maps >> Campus Buildings & My Destinations

**To Reproduce**
1. Select Maps 
2. Select Campus Buildings (and My Destinations) from Drop Down Menu
3. Error: Campus map will display with many building names missing even when zoomed in (e.g., Follinger Hall, English Building, Henry Administration Building)

**Expected behavior**
Names of buildings should display when map is zoomed in.

**Screenshots**

![No Building Names in Campus Buildings](https://user-images.githubusercontent.com/118769169/230637574-c488c4ff-b6cc-439f-babc-6cae5e349859.png)

![No Building Name in _My Destinations](https://user-images.githubusercontent.com/118769169/230637593-138a1ff7-4b19-4039-a3ee-5e7c06ddbbf7.png)

**Smartphone (please complete the following information):**
 - Device: Android
 - Version [4.3.34]

**Comment by mihail-varbanov** [comment]
@knguyenjahiel, this behavior is by design. I was requested when we show Campus Buildings to disable Google Maps for displaying its own internal points of interest. The reason for this, as long as I remember, was that our POI markers overlapped theirs and it did not look well. We also wanted to disable building levels, which was achieved by this as well. But if we decide that we want buildings visible I can turn this off. @pmarkhennessy ^

**Comment by knguyenjahiel** [comment]
I understand. I'll close this item for now and bring it to Design & Research Team to explore another option to allow users to find/locate Campus Buildings. Thanks
