### ISSUE TITLE
[BUG] Map fails to display when a course location is selected in My Courses

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3100]
**Describe the bug**
The map does not display when the location of a course is selected in My Courses.

**To Reproduce**
1. Touch 'Academics'
2. Select 'My Courses' >> Spring - 2023
3. Find 'Arts at Illinois'
4. Touch 'Amory, Room 243'
5. Error: Map fails to display to show the location of the Amory

**Expected behavior**
Map showing the location of the building where a course is located should display when location/address is touched.

**Screenshots**
![Location Link to Map](https://user-images.githubusercontent.com/118769169/230640624-658090d3-f0f2-42b8-8521-84b915cfd056.png)

**Smartphone (please complete the following information):**
- OS: Android
- Version: 4.3.34

**Comment by mihail-varbanov** [comment]
Resolved in version 4.3.46.

**Comment by knguyenjahiel** [comment]
Tested in version 4.3.47: map still failing to display.

**Comment by mihail-varbanov** [comment]
This happens because we have building for student course but its geolocation is invalid (zero latitude/longitude). What I did was to display location info as plain text instead of as underlined link in this case, so it is cleat to the user that it is not tappable. This fix will be available in version 4.3.48.
