### ISSUE TITLE
[BUG] Please reconnect 24 Hour Crisis Resources in Wellness Menu

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3282]
**Describe the bug**

The menu item _Wellness > Wellness Resources > 24 Hour Crisis Resources_ shows "Empty Guide Content".

It should point to the following article: _Campus Guide > General Support > 24-Hour Crisis Resources_.

This Campus Guide article was accidentally deleted, and we had to recreate it. Therefore the article has a new ID:  "_id": "9214bef9-4cb3-4596-ae1f-aa6e8261d2f0", (If I'm looking at the right number in Guide JSON Structure.)

Please point the menu item to the new version of the article.

![24-hour crisis resources](https://github.com/rokwire/illinois-app/assets/66988329/c66dbee9-36f4-4fdb-a6fc-b1492b542f4d)

....
Comment: This problem was caused by an attempt to edit the article using the Admin webapp. Any Save to an existing article causes deletion. (Or, at least, loss of our ability to find the article.) We knew about this bug in Admin webapp, but one of our group forgot and used it yesterday.

This "delete when saving" bug in webAdmin is causing us and devs a lot of wasted time. It is the reason for this issue: https://github.com/rokwire/illinois-app/issues/3229. 

When a guide item is deleted, we have to recreate it from scratch. It gets a new ID, and then links to the item from different places in the UI outside the campus guide no longer work.

**Comment by mihail-varbanov** [comment]
I initially tried to change the ID of "24-Hour Crisis Resources" article on production back to "ddd2f4e7-b976-4bd0-9998-f2e16c0f7823" but Content service failed to do this, I do not know why.

So I changed the ID of this article on dev to "9214bef9-4cb3-4596-ae1f-aa6e8261d2f0", so that to match what we have on production, and updated wellness resource content to refer to this new guide article ID. Everything looks good to me now both on production and dev.

@pmarkhennessy, @mdryankov, @dobromirdobrev, #3229 illustrates the same problem. What we currently have is just a pain. We have to do something with the guide article IDs. The item identifiers that the client uses should be separated from the MongoDB IDs, and the backend service should not deal with the client identifiers in any way. This will allow us to keep guide content consistent across environments, as well as the links to guide articles from the different sources.

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, @mdryankov, @dobromirdobrev, #3229 illustrates the same problem. What we currently have is just a pain. We have to do something with the guide article IDs. The item identifiers that the client uses should be separated from the MongoDB IDs, and the backend service should not deal with the client identifiers in any way. This will allow us to keep guide content consistent across environments, as well as the links to guide articles from the different sources.

**Comment by joegrohens** [comment]
Looks good now in both prod and dev. Thank you.
