### ISSUE TITLE
[BUG] Student Guide - Same information is repeated in different category

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#329]
**Describe the bug**
Student Guide - The "Book" is information is placed Under Academic support and in New Student section too. The same applies to "Dining, Housing, and Financial Support"

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and verify the role as a student role
3. Via browse screen, navigate to Student guide 

**Actual Result**
The "Book" is information is placed Under Academic support and  New Student section too. The same applies to "Dining, Housing are placed under 'Living on Campus" and New Student section too. "Financial Support" is placed under the Financial and legal and New Student section too.
Tech Resource and Tech support is also placed under Tech and New Student section too

**Expected behavior**
To avoid confusion to the user it would be good not to repeat the same information in a different category.

**Screenshots**
![Repeating](https://user-images.githubusercontent.com/26231179/122967904-96749800-d350-11eb-9153-6129d5c2d654.png)

**Smartphone (please complete the following information):**
Device: [e.g. Android]
Version [e.g. 2.4.25]

**Additional context**

**Comment by joegrohens** [comment]
@Priyaravi8 @isaac-galvan @pmarkhennessy 
Cross-indexing the information pages under multiple topics is an intentional feature of the information design. 

I'm not saying I agree with this pattern of organization. But it is not a bug.

I suggest that you leave this issue open, but re-tag it as a usability question.  

We should do usability testing to develop data that will help us evaluate the usability of the classification method for browsing through these pages. 

Joe
