### ISSUE TITLE
[BUG] Favorites icon slightly different color

### ISSUE THREAD

**Issue by JosephShepin** [rokwire/illinois-app#3317]
Notice that the star above the "favorites" text on the bottom nav bar is a lighter gray than all the other icons that are not currently selected. 

![Screenshot_20230603-233307](https://github.com/rokwire/illinois-app/assets/31457361/56903b95-1262-450a-98fe-f162353b09da)

Android 13, Pixel 7

**Comment by TodorBachvarov** [comment]
All icons used in the Nav Bar are with the same colour: MediumGray. 
  "star-outline-gray": {"src": "images/icon-star-gray-frame-thin.png", "type": "flutter.asset", "color": "mediumGray", "size": 18},
  "campus-tools-outline-gray": {"src": "images/tab-browse.png", "type": "flutter.asset", "color": "mediumGray", "size": 18, "todo": "size"},
"location-outline-gray": {"src": "images/tab-navigate.png", "type": "flutter.asset", "color": "mediumGray", "size": 18, "todo": "size"},  etc.

My assumption is that the favorites icon is slightly thinner that the rest icons. 
In order to fix this I'll need new icon resource  with the appropriate size. @pmarkhennessy, could you redirect this issue to the designers team for assistance.

**Comment by TodorBachvarov** [comment]
@vburgett  we will need new icon resource.

**Comment by vburgett** [comment]
This is fixed in version 5.1.34.
