### ISSUE TITLE
[BUG] Revert Event Title on Details Panel Back to Extra Bold 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3433]
Please revert the event title on the event details panel back to extra bold. In the below screenshot, "Broken External Registration" should be extra bold like the second screenshot "Caffettino."

IL app v.5.0.33

 
![Screenshot_20230724-120818](https://github.com/rokwire/illinois-app/assets/1044905/c3812d5a-087d-4e1b-9da9-5c8123ca7414)

![IMG_5281](https://github.com/rokwire/illinois-app/assets/1044905/e5f39d6a-0fa3-4f00-9fe9-bd56a618c7e0)
d51)

**Comment by mihail-varbanov** [comment]
I do not think we should really do this.

@TodorBachvarov put effort to standardize widget text styles across the UIUC app. Currently calendar events, athletics news, dining locations or appointments use the same text styles scheme that gives similar look and feel of their detail panels:

I agree that there are other detail panels (like group or guide article) that use different text styles scheme, where the titles are semi/extra bold, but I would add that they generally represent a different model category.

I think we should put our efforts towards standardizing and unifying the UI across the app instead of making local and specific changes.

CC @pmarkhennessy.

![Screen Shot](https://github.com/rokwire/illinois-app/assets/5631487/3c88ade3-2d5f-4dce-b771-b326ae9f98e9)

![Screen Shot2](https://github.com/rokwire/illinois-app/assets/5631487/a64e7541-bffe-4499-a694-e5ebce7e4baf)

**Comment by pmarkhennessy** [comment]
@vburgett This needs to be deferred until after the initial 5.0 release and as Misho says, we should do a full sweep.
