### ISSUE TITLE
[BUG] Event Date and Time Filter Not Working


### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3518]
Under Events Feed, choose Filter, Date and Date, Custom. Pick start and end dates and times. See how Apply/Clear UI is missing. Tap the back arrow to return to the Date and Time  options and see how Custom is no longer selected but the setting has reverted back to Upcoming. Events are not filtered by the custom time. 

I expect a custom Date and Time to filter by the dates and times specified. 

Version 5.0.53
Android 13, Pixel 6

![Screenshot_20230810-113301.png](https://github.com/rokwire/illinois-app/assets/1044905/87ad5cfe-3deb-4368-b2f8-9908571109f7)

![Screenshot_20230810-113245.png](https://github.com/rokwire/illinois-app/assets/1044905/f03db5ae-9626-417d-a2b1-7ecf569ac799)

**Comment by mihail-varbanov** [comment]
The fact that you did not see the Apply button means that Apply was not available. It could not be available if nothing is selected / changed, if start or end time is in the past, or if end time is before the start time. I consider that this may be confusing for the user (as your case) and that's why I changed the behavior of this panel to show Apply button always if there is a modified content. If the apply is not available it is displayed in grayscale color and taping on it displays an error message explains why apply is not available. This update is available in version 5.0.46.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov!
