### ISSUE TITLE
[BUG] Error when starring events 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3519]
**Use case:** a user does _not_ want to add events to their calendar but _does_ want to favorite events within the Illinois app
**User experience in v5.0.43:** the user receives the error "Unable to save event to calendar. Permission not granted." when starring and unstarring an event in the Events Feed, My Events, or a specific event detail panel with every combination of their My Calendar Settings. 

Expectations: A user should not receive this error when starring or unstarring events regardless of their My Calendar Settings. 

Making this a high priority since we will be directing a large group of attendees to star events and use "My Events" during the upcoming Illini Fest. 

Attached is the error and the provided 5.0 solution for detaching "Add to Calendar" from the star functionality. 

5.0.43
Android 13, Pixel 6

![Screenshot_20230810-122507](https://github.com/rokwire/illinois-app/assets/1044905/36e3bc31-d06a-4a1e-b842-6f194d8481ad)

![Screenshot_20230810-122515](https://github.com/rokwire/illinois-app/assets/1044905/a5aa79df-0583-4364-8dca-9897d594d229)

<img width="947" alt="Screenshot 2023-08-10 at 12 25 52 PM" src="https://github.com/rokwire/illinois-app/assets/1044905/83b18749-82ec-4a7d-9964-32c79b5e2775">

**Comment by mihail-varbanov** [comment]
I am not sure what is exactly expected in this issue - not to attempt to store the event to Calendar, or just to suppress the error message?

I tested this using UIUC 5.0.45 running on iOS and it works well for me.

1. If Settings / My Calendar Settings / "Add saved events to calendar" is off the application does not attempt to save events to calendar when they get marked as favorite.

2. If Settings / My Calendar Settings / "Add saved events to calendar" is on it attempts to save them. If "Prompt when saving events …" is ON we get prompted first.

3. The only way to get the "Unable to save event to calendar. Permissions not granted" message if "Add saved events to calendar" is on but the permission to access the Calendar is disabled from System Settings. In my opinion in this case we properly show the toast message in order to indicate that the UIUC setting requires saving the event to the Calendar but the system permission does not allow this, so that the user is able either to turn off the "Add saved events to calendar" setting or to grant the needed permission.

In addition to events we also add to Calendar Games, Guide Items, Appointments and Canvas events. If the purpose of this issue is not to attempt to store favorite events to Calendar, this will also affect the above items as well. If the purpose is just not to show the error message, I can do this very easily but the user will lose the feedback, in my opinion.

**Comment by pmarkhennessy** [comment]
@vburgett This has been implemented in 5.0.48 and above. Star is for saving to My Events and Add to Calendar is what is says now.

**Comment by vburgett** [comment]
Thank you! Confirmed as working in 5.0.52.
