### ISSUE TITLE
[BUG] Repeat Health Screener Notifications

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3597]
I tested the health screener back in March 2023. Since then I have received numerous, periodic notifications to rescreen for a sore throat. Among others, I recorded receiving a notification on May 2, May 16, and June 20. Is this by design or a bug?

As a user, I want the notification about a 5-month old symptom to stop. 

4.3.61
iPhone 13, iOS 16.6

![image](https://github.com/rokwire/illinois-app/assets/1044905/0c12cd11-fd4c-4849-a676-dbba5ec3d4e6)

![image](https://github.com/rokwire/illinois-app/assets/1044905/00c36f44-42e9-41db-b8fb-12474ccc5ae1)

**Comment by roberlander2** [comment]
Thank you for catching this @vburgett. The notification was set to repeat weekly unintentionally. I made a fix so that it should only be sent once: https://github.com/rokwire/app-flutter-plugin/pull/366.

**Comment by vburgett** [comment]
@roberlander2 should this update be in effect with v4.3.61 or 5.0?
I received another strep rescreen reminder on 8/29/2023 at 2pm via 4.3.61.

**Comment by roberlander2** [comment]
@vburgett, this issue should be fixed in v5.0.55 or greater, so you will need to update your app. Unfortunately, I think you will need to take the strep screener again (or a different symptom in the health screener that schedules a rescreen notification) because the repeating notification will not stop unless it is overwritten, or by disabling app notifications entirely.
