### ISSUE TITLE
[BUG] Appointment locations are losing the decimal places of lat/long coordinates

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#3604]
**Describe the bug**
Appontments -> McKinley appointments are taking students to homer lake. I have verified that the location coordinates coming out of the data push are this:
"location": {
		"id": "McKinley Health Center, Womens Health Clinic, Second Floor",
		"title": "McKinley Health Center, Womens Health Clinic, Second Floor",
		"latitude": 40.10295291956433,
		"longitude": -88.21989804371852,
		"phone": "217-333-2700"
}
but in the app, when selecting the location for the McKinley appointments, the app switches to Google Maps and navigates to 40.00000000 and -88.0000000, which is Homer lake.

**To Reproduce**
1. Go to appointments -> My McKinley appointments
2. Click into one of the appointments
3. click on the location of the appointments

**Expected behavior**
The user shoudl be navigated to McKinley health center

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS and Android 
 - Version 4.3.61

**Comment by mihail-varbanov** [comment]
Hi @clint156, I do not have any scheduled appointments in McKinley and that's why I made my test with [sample JSON content](https://github.com/rokwire/illinois-app/blob/develop/assets/extra/appointments.json) having the same location as the mentioned one above. I was not able to recreate the problem that you describe neither on 4.3 nor on 5.0 version. In both cases the application launches the following URL: https://www.google.com/maps/dir/?api=1&destination=40.102910,-88.219610&travelmode=walking

 Is it sure that the locations come to the UIUC app with the above real number coordinates? Can you provide a scenario that I could recreate, or can provide the JSON content that was used when the problem had been observed?

**Comment by clint156** [comment]
@mihail-varbanov I just pushed an appointment to your account in dev. I can do it to production if you would like. Here's the JSON that I'm showing was pushed up:
[{
	"source_id": "1015627",
	"provider_id": "1",
	"appointment_date_time": "2023-08-22T13:45:00.000Z",
	"cancelled": false,
	"type": "InPerson",
	"location": {
		"id": "McKinley Health Center, Immunization and Travel Clinic, First Floor",
		"title": "McKinley Health Center, Immunization and Travel Clinic, First Floor",
		"latitude": 40.10295291956433,
		"longitude": -88.21989804371852,
		"phone": "217-333-2700"
	},
	"account_id": "c20a9811-038a-11ee-9b71-0a58a9feac02",
	"host": {
		"first_name": "Schedule 3",
		"last_name": "Nurse"
	},
	"online_details": null,
	"instructions": ""
}]

**Comment by mihail-varbanov** [comment]
Thank you very much, @clint156 - I just saw the issue for first time!

The problem appears to be in our appointments BB because this is what the UIUC client app gets as an appointment content:
```
GET https://api-dev.rokwire.illinois.edu/appointments/services/appointments?end-date=1692714537509&order=desc
[
  {
    "answers":null,
    "cancelled":false,
    "date":"2023-08-22T13:45:00Z",
    "host":{
      "first_name":"Schedule 3",
      "last_name":"Nurse"
    },
    "id":"02d1bed2-4441-4e18-8165-9aec1d3a66d8",
    "instructions":"",
    "location":{
      "id":"1_McKinley Health Center, Immunization and Travel Clinic, First Floor",
      "latitude":40,
      "longitude":-88,
      "phone":"217-333-2700",
      "title":"McKinley Health Center, Immunization and Travel Clinic, First Floor"
    },
    "provider":{
      "canceling":false,
      "id":"1",
      "name":"McKinley",
      "rescheduling":false,
      "scheduling":false
    },
    "type":"InPerson"
  }
]
```

I am closing this issue and opening a new one in appointments BB repo: rokwire/appointments-building-block#98

Thanks again for all your help!
