### ISSUE TITLE
[BUG] Webtools' event images not in the app

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3607]
Images uploaded to Webtools events are not pulling into the Event Feeds or the event details panel in the app. 

See the "We Belong Festival" event on 9/12 in the app and via [Webtools](https://calendars.illinois.edu/search/6991?go=go&listType=summary&startDate=08%2F21%2F2023&endDate=12%2F31%2F2099&searchEventType=&KEYWORDS=Festival%2FCelebration). 

v 5.0.47
Android 13, Pixel 6

**Comment by sandeep-ps** [comment]
Hi, @vburgett, I have created a bug report in the Calendar BB. For this event and a few others, I verified that the image URL exists in the Events data from the old Events Manager and Events BB. This could be related to data migration or due to image URLs getting lost during an event update, which was a week or so ago.

**Comment by vburgett** [comment]
@sandeep-ps the images are still not being displayed in the app v5.0.62. Any updates?

**Comment by sandeep-ps** [comment]
The related backend issue https://github.com/rokwire/calendar-building-block/issues/307 was closed with code changes. According to Petyo's comment, it should have been fixed. I have created a [new](https://github.com/rokwire/calendar-building-block/issues/337) bug report in the Calendar BB. The image URL in the Events BB looks right.

**Comment by vburgett** [comment]
Confirmed as fixed in 5.0.68. Thank you!
