### ISSUE TITLE
[BUG] Event cost description field can't be edited 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3658]
After creating an event in the app, the event cost description field cannot be updated via "edit event." An admin can enter an edit and choose "update event," but the edit is not saved or reflected in the event detail panel.

V5.0.55
Android Pixel 6

**Comment by mihail-varbanov** [comment]
I can confirm that this is a backend issue. I created a ticket for it (rokwire/calendar-building-block#321) and closing this one.

**Comment by vburgett** [comment]
In 5.0.62 editing the cost description still does not save. @mihail-varbanov @TodorBachvarov

**Comment by mihail-varbanov** [comment]
@vburgett, as I explained above this is an issue in the backend, not in the client application. There is nothing to do in the client application regarding this issue, it must be fully resolved in the Calendar BB. Until it gets resolved there whatever  UIUC version you try on the problem will persist. That's why please stop reopening this issue and monitor its status in rokwire/calendar-building-block#321. CC @pmarkhennessy.
