### ISSUE TITLE
[USABILITY] Clarifications between Event Registration and Event Attendance

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3678]
To clarify how event registration and event attendance work and are _not_ dependent upon one another, please make the below updates.

When creating and editing **event attendance** settings, please:
- update the first instance of "check" to "taking"
- change "Registrants" to "Guest List"
- shorten info text under the Guest List to "Visit https://go.illinois.edu/AppAdmin to upload or download a list."  
- change "NetID for manual attendance check" to "Add NetID to the guest list"
- add hyphens (A space- or comma-separated list of NetIDs.")

When creating and editing **event registration** settings, please:
-add the Guest List dropdown and info text above the "NetIDs for additional registrants"
-change "NetIDs for additional registrants" to "Add NetID(s) to the guest list"

v5.0.57 
Android Pixel 6

![Screenshot_20230829-154848-final](https://github.com/rokwire/illinois-app/assets/1044905/a628a749-3cdb-4e52-91c6-a875cb79d8fa)

![Screenshot_20230829-154821-final](https://github.com/rokwire/illinois-app/assets/1044905/ed542d51-774b-45dc-9133-9a09eb69a719)

Cc: @kpecknold

**Comment by TodorBachvarov** [comment]
Done in version 5.0.62. 
I want to mention that there is a small change regarding this request: 
"When creating and editing event registration settings, please:
-add the Guest List dropdown and info text above the "NetIDs for additional registrants" 
I've added the "Guests List" but instead of showing radio button (to mark the user who was attending to this event) we show the status of his registration, if he was self registered or added from the "ADD NETID(s) TO THE GUEST LIST" edit box. Also the netid added from the edit box is not validated from the backend so even if the added net id is not valid, we will still show it in the guests list. 
Also the backend do not provide capability for the admin to unregister the other users so we can't add the Radio Button (as for attendance) because there will be no suitable backend functionality to hook it.

**Comment by TodorBachvarov** [comment]
Fixed. Now we show only participants in the guest list (Self Registered/Guest List). The Attendance takers will be visible in the Attendance Panel(s).

**Comment by vburgett** [comment]
Thank you!
