### ISSUE TITLE
[BUG] single event appears multiple times

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3753]
**Describe the bug**
v5.0.68 prod

I created a single non-recurring event. It is displayed 10 times in the Events search results.

You can see it at **Browse > Events > All Events > Eat at Joe's.** (it ends Sept 20, 2023)

![multiple appearances of same event](https://github.com/rokwire/illinois-app/assets/66988329/69976894-6923-4f08-8940-2e654f964990)

**Comment by joegrohens** [comment]
Additional details, now that I see others are experiencing the same problem.

- I had set registration to on.
- Attendance by scanning and manual both.
- I had tried to create an event survey, but that failed, so I reset event survey to none, in order to enable the "create event" button.

**Comment by joegrohens** [comment]
Follow-up.

Using 5.0.69, I tried one time without adding a survey. The events were not multiplied.

Then, again in 5.0.69, I tried adding a survey, which failed. And that event multiplied.

**Comment by joegrohens** [comment]
Immediately after, again in 5.0.69, I created an event called "Can I break event"

I _did_ try to add a survey, which failed, and so I reset survey to none in order to be able to create the event. That event did multiply.

Therefore, maybe the failed attempt at adding a survey is implicated in the duplication.

Other settings for "Can I break" were:
- public
- registration required
- attendance is enabled by scanning and manual
- Date is set to 9/20/23

![can i break](https://github.com/rokwire/illinois-app/assets/66988329/1e86246d-79d5-4d90-b1c8-d63e4ac2731a)



![can i break](https://github.com/rokwire/illinois-app/assets/66988329/b2cdd951-6405-466a-bfbe-738d9fc3d013)

**Comment by vburgett** [comment]
An event created in the app that has a survey set gets published every time the user taps the Create Event button and receives the “Failed to create survey” error (related to #3757). To repeat:

1) create an event in the app under All Events
2) fill out the required fields and add a survey
3) Tap Add Event
4) see Failed pop-up
5) Tap Add Event again
6) see Failed pop-up
7) remove survey setting
8) tap Add Event and event publishes
9) search for your event under All Events and see that there are now two instances of the event

**Comment by mihail-varbanov** [comment]
@vburgett, first thank you for the precise problem description. It was very helpful indeed!

It was a combination of two software problems:

1\. The survey creation used to fail on production due to some configuration issues. @shurwit should have fixed this as he says [here](https://github.com/rokwire/illinois-app/issues/3757#issuecomment-1726431343).

2\. We fall into the following situation: we created the new event successfully but failed to associate its survey (this happens on two independent requests to the backend). We properly informed the user about the survey creation failure but we behaved like we failed to create the whole event that was not true. 

@roberlander2 fixed this for #3758 by always loading the event detail panel after successful event creation, nevertheless the survey association failed or not, and still alerting the user in case of failure. Now the user is aware about what is going on and is able to try again the survey association using the event admin commands.

I consider that this is not the best UX but I think that it is the best we can do in the current situation. Please review the updated app version 5.0.70 and see if it resolves this issue.

**Comment by roberlander2** [comment]
Hi @vburgett, just want to clarify a couple of things:

The event details panel will be shown _after_ the user acknowledges or dismisses the survey creation error message (which appears on the event creation panel).

The message is still "Failed to create event survey.", as shown in #3757. The message is only for survey creation failures, so it can be updated to what you suggested if the current message is not already close enough. Let me know what you think.

Thanks!

**Comment by vburgett** [comment]
@roberlander2 thanks for the clarifications. Both work as is for me for the 5.0 release.
@joegrohens do you have any comments on the wording? I am good with closing this ticket when you are.

**Comment by joegrohens** [comment]
Confirmed fixed. I did not get an error about creating the survey. The event was not duplicated.

Ryan: the “Failed to Create Event Survey” wording is fine with me.

Closing this issue. Thanks, all.
