### ISSUE TITLE
[BUG] Event admin can't access survey results

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3768]
I created an event with registration, attendance, and a survey called "An Event" for 9/26/23 at noon CT. I cannot access survey results from the app (5.0.70 Android) or the web admin (calendar 1.50.00).  

When an event admin needs to access an event that has passed to view the survey results, where should they be able to do so? At one point, the event admin received a notification about the survey which allowed them to access the event and survey results in the app. Today I did not receive the notification about the survey, as the event admin. (Attendees _did_ receive the notification.)

I logged in via the web admin, and I did not see this past event.

Event admins should be able to see their past events in the web admin and the app via My Events in order to access their survey responses.

**Comment by pmarkhennessy** [comment]
@dobromirdobrev Can you check this please

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

The Illinois app is not designed to show past events. So if an event had passed, the user won't be able to see in the UI of the app. 
The same logic is applied in the Admin app - it shows only current/upcoming events.

So this is not a bug but it is how the Illinois app is designed. 

If we want to see the survey results for a past event then we will need a relevant UI design of how this should look like and to implement it in the app. So I would say that this should be a feature issue rather than bug. cc @pmarkhennessy

**Comment by mihail-varbanov** [comment]
I believe https://github.com/rokwire/illinois-app/issues/3845 refers the same problem.

**Comment by vburgett** [comment]
Past events and survey results can be accessed via the admin website. Until we have a need for a solution in the Illinois app, this ticket is no longer relevant.
