### ISSUE TITLE
[USABILITY] Match event admin settings in the app with the admin website

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3876]
As requested, I have compared the event admin settings in the app and on the admin website. Here is a list of items that need updating in the app to match the admin website.

1. arrows on the “Create an event” screen should point right. (They now have a caret pointing up indicating the sections are expandable when they are not.) 
2. add “Event Admins NetIDs (comma separated)” field
3. Change “Is this event free?” to “List event as free”
4. match Event Registration “via the app” to the Event Admin Settings > Event registration screen. In both registration screens, change “Add NetID(s) to Guest List” to “Add and register NetID(s)”
5. change purple background color of pop-up windows to white
6. under “edit event” match Event Attendance options to the app event screen under Event Admin Settings and Event Attendance. On both app attendance screens, change “Add NetID to the guest list:” to “Add NetID(s) as attended:”
7. under Event Follow-up Survey match the Survey Preview UI/UX to the admin website. (Ideally tapping on the “Survey Preview” block would advance to a new panel.)
8. add “Illinois App Groups” block for adding events to Group(s) instead of using a pop-up (pending outcome of ticket #402 https://github.com/rokwire/illinois_admin/issues/402)
9. Under Events, add to the bottom of the “Event Filters” panel the info icon with the text “How are events published in the Illinois app?” The entire question should be underlined and linked to Campus Guide, App Help, Adding Events. 
10. under Event Attributes, change the word “group” to “event” under “College, School & Unit” and “Department”

Illinois app v5.1.11

Matching admin website issues Git ticket: https://github.com/rokwire/illinois_admin/issues/509

**Comment by mihail-varbanov** [comment]
Wow, this is a real story or epic ticket in Jira terms!

Now on each separate request:

**1. arrows on the “Create an event” screen should point right. (They now have a caret pointing up indicating the sections are expandable when they are not.)**
Done for those sections only that do panel navigation (e.g. Event Attributes, Registration, etc.). Not done for expandable sections like Date and Time or Type and Location. Available in version 5.1.13.

**2. add “Event Admins NetIDs (comma separated)” field**
The current Calendar BB client API does not support this so it is not possible to be done in short terms.

**3. Change “Is this event free?” to “List event as free”**
Done in version 5.1.13.

**3. match Event Registration “via the app” to the Event Admin Settings > Event registration screen. In both registration screens, change “Add NetID(s) to Guest List” to “Add and register NetID(s)”**
3.1. I do not see differences between Illinois and Admin apps except the ability to upload registrant 

**NetIds from an external file. Is this what is meant by "match"?**
3.2. The text change is implemented in version 5.1.13

**4. change purple background color of pop-up windows to white**
Done in version 5.1.13.

**5. change purple background color of pop-up windows to white**
Done in version 5.1.13.

**6. under “edit event” match Event Attendance options to the app event screen under Event Admin Settings and Event Attendance. On both app attendance screens, change “Add NetID to the guest list:” to “Add NetID(s) as attended:”**
Done in version 5.1.13.

**7. under Event Follow-up Survey match the Survey Preview UI/UX to the admin website. (Ideally tapping on the “Survey Preview” block would advance to a new panel.)**
Done in version 5.1.13.

**8. add “Illinois App Groups” block for adding events to Group(s) instead of using a pop-up (pending outcome of ticket Feature/issue 387 #402 [FEATURE] Ability to publish an event to multiple Groups for which you are an admin illinois_admin#402)**
Done in version 5.1.13.

**9. Under Events, add to the bottom of the “Event Filters” panel the info icon with the text “How are events published in the Illinois app?” The entire question should be underlined and linked to Campus Guide, App Help, Adding Events.**
I am not sure I understand clearly what is wanted here. From what I read I understand that you want this link in the panel that we open from the "Filters" button in the Events home panel. However, in my opinion, the publishing details are important for those who create events, not for those who browse and filter events. Also, this issue is for administering events, not for event filters, so I guess there might be something wrong with this request.

**10. under Event Attributes, change the word “group” to “event” under “College, School & Unit” and “Department”**
This is difficult to be done quickly because the “College, School & Unit” and “Department” attributes definitions are shared between Groups and Events. We can either use some neutral wording that does not refer neither groups nor events, or extend the attributes model to support different description texts depending on the the scope they are used (events or groups).

**Comment by vburgett** [comment]
3. See below screenshots and recording for the two different event admin registration screens in the app. 

9. I'll put in a new ticket for this one. 

10. Let's go neutral.
Choose a college, school, or unit:
Choose a department:

https://github.com/rokwire/illinois-app/assets/1044905/0abc9ca8-5b25-4b98-90cb-271bade3eeae

![Screenshot_20240124-084410.png](https://github.com/rokwire/illinois-app/assets/1044905/92317294-f189-47c1-aa43-9fa02f550add)

![Screenshot_20240124-084430.png](https://github.com/rokwire/illinois-app/assets/1044905/c2e922d3-d461-44e8-8743-b2b80800b534)

**Comment by mihail-varbanov** [comment]
**3. match Event Registration ...**
_See below screenshots and recording for the two different event admin registration screens in the app._
I think I got what you mean. This should be fixed in version 5.1.14

**10. under Event Attributes, change the word “group”...**
_Let's go neutral._
The neutral wording is acknowledged in content BB on dev/test/prod (these strings do not reside in the client app).

**Comment by vburgett** [comment]
Confirming all but 10 has been reviewed and is completed. I will wait for the content BB updates to be in place to close this ticket.

**Comment by vburgett** [comment]
Complete in 5.1.17.
