### ISSUE TITLE
[BUG] Group members publishing events needs admin setting 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3921]
Currently group admins and members can publish an event to ANY group they are a member of including hidden administrative groups like the MTD bus pass group (see below screenshot).

Group members and admins should not be able to publish an event to a hidden administrative group. 

Group members should not be able to publish an event to any Group without first implementing a Group-specific setting "Only admins can create Group events."

5.1.18

![Screenshot_20240131-155112.png](https://github.com/rokwire/illinois-app/assets/1044905/2ebc4fb2-3ead-4722-9df0-546edad7aa48)

![Screenshot_20240131-154315.png](https://github.com/rokwire/illinois-app/assets/1044905/0aeed840-40f5-439a-99ba-a53065b92287)

![Screenshot_20240131-160101.png](https://github.com/rokwire/illinois-app/assets/1044905/672618e7-a6ed-4fa4-a08f-044f26139b99)

**Comment by mihail-varbanov** [comment]
@vburgett, currently ONLY admins (and NOT members) can create event to any group. I'm a bit torn on what exactly you want:

1. Forbid to ANYONE, including admins, to post events in managed membership groups. I do not find this reasonable, because my belief is that we should not restrict admins in any way - that's why they are admins.

2. Introduce a new Advanced Group Setting "Only admins can create Group events", that will allow regular group members to also post events in that group (if this new flag is turned off, of course).

Could you please define precisely what you are expecting to happen exactly in the Illinois app?

**Comment by vburgett** [comment]
@mihail-varbanov When I create an event via the app and go to publish my event to various Groups, I see nine Groups listed (see above screenshot). I am an admin for three out of nine of those groups. The issue is if only admins can publish to Groups, I should not see the other six Groups listed to publish my event to. 

I am an admin of Super Secret Private Group, Would you rather . . . , and Groups Hangout.

**Comment by mihail-varbanov** [comment]
Thanks @vburgett, I got it now. This had been fixed in version 5.1.20.

**Comment by vburgett** [comment]
This worked. I tested creating an event in the app from All Events _and_ from within a Group. I only saw the option to publish to Groups that I administer, as expected. Thank you, @mihail-varbanov!

5.1.20 Android
