### ISSUE TITLE
[BUG] Error displays up on Registering on an Event

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3937]
**Describe the bug**
Tap on the Register button in the Event screen, Error is displayed to the user.

**To Reproduce**

Create an Event Via Illinois Dashboard
users Netid's are not registered but are added as an Attendee
Publish the Event
On the APP side - The event displays to the NetID in the Attendee list with the Register button.
Tap on the Register button

**Actual Result**
An error message is displayed to the users.

**Expected behavior**
The user should be able to register for the event without error

**Screenshots**
![Failure registeration](https://github.com/rokwire/illinois-app/assets/26231179/3623b3a0-9013-4d58-9d08-45540b2123e9)

**Smartphone (please complete the following information):**
Device: [e.g. Android]
App Version: [e.g. 5.1.19]

**Additional context**

**Comment by Priyaravi8** [comment]
@mihail-varbanov - I still reproduce this issue

**Comment by vburgett** [comment]
@mihail-varbanov noting that Priya gets the same registration error for a "Group Members Only" event I created from the app in the group "Groups Hangout" on dev 5.1.25.

**Comment by mihail-varbanov** [comment]
@vburgett, @Priyaravi8,

My feeling is that when I first read this issue there was nothing about registration / attendance settings set to this event. Anyway, even applying them as described in the issue, I was again unable to recreate this problem. That's why, please describe each step that you have done, e.g.

1. In Admin app, logged in as …, go to "Events Calendar" 
2. Choose "Create"
3. Fill the event details:
- Input "..." for EVENT TITLE;
- Input "..." for DATE AND TIME;
- Input "..." for TYPE AND LOCATION;
…

4. Select Save button
5. …
6. … 
…

I would like to know to every single step/action taken before obtaining this error screen.

CC @pmarkhennessy

**Comment by Priyaravi8** [comment]
https://github.com/rokwire/illinois-app/assets/26231179/c5f12ba2-a94e-4739-8b38-dc2d2edda082

**Comment by vburgett** [comment]
[Screen recording of creating the "Group Member Only" event via the admin website.](https://github.com/rokwire/illinois-app/assets/1044905/355cdbc0-fdf1-4c94-98f3-727f296846f2)

**Comment by mihail-varbanov** [comment]
@vburgett, @Priyaravi8, thanks for the good recreation scenario! Now I managed to recreate the bug. The key information that I obtained right now was that the event is a group's private event. For regular events the registration works fluently.

This is a backend issue. I will close this ticket and open the relevant one in the Calendar BB repository.

CC @pmarkhennessy.
