### ISSUE TITLE
[BUG] Students cannot see the Groups for which they are Admins in the Ill App Admin Dashboard >> Events 

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#4074]
**Describe the bug**
Students who have access to the Ill App Admin Dashboard to create Events do not see their Groups for which they are admins. They receive an incorrect message: You are not an admin of any groups. Consequently, they cannot link their Events to their Groups.

**To Reproduce**
1. Add a student to the authman group that has permission to create events. For testing purposes, I granted permission to testory3.
2. Add a student to a Group for which you are an Admin. For testing purposes, I added testory3 to "Kathryn" group.
3. In Ill App Admin Dashboard, create an event.
4. Add student as an Admin of the event. I added testory3 to Test Group Link Event
5. Have student select "Illinois App Groups"
6. Student will see: You are not an admin of any groups.

**Expected behavior**
Students who have permission to create Events in the Ill App Admin Dashboard, and are Admins of Group(s) should be able to see their groups in order to link their events to their groups.

**Additional context**
Events Calendar BB 1.67.0 prod.

**Comment by knguyenjahiel** [comment]
This bug has been submitted to the appropriate illinois-admin space.

**Comment by kpecknold** [comment]
Kim,
I think I might have casued this. I think I removed testory3 from the Kathryn group because I didn’t know who they were. Can you re-add and re-test?
Kathryn

From: Kim Nguyen-Jahiel ***@***.***>
Sent: Tuesday, May 21, 2024 10:44 AM
To: rokwire/illinois-app ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rokwire/illinois-app] [BUG] Students cannot see the Groups for which they are Admins in the Ill App Admin Dashboard >> Events (Issue #4074)


Describe the bug
Students who have access to the Ill App Admin Dashboard to create Events do not see their Groups for which they are admins. They receive an incorrect message: You are not an admin of any groups. Consequently, they cannot link their Events to their Groups.

To Reproduce
Steps to reproduce the behavior:

  1.  Add a student to the authman group that has permission to create events. For testing purposes, I granted permission to testory3.
  2.  Add a student to a Group for which you are an Admin. For testing purposes, I added testory3 to "Kathryn" group.
  3.  In Ill App Admin Dashboard, create an event.
  4.  Add student as an Admin of the event. I added testory3 to Test Group Link Event
  5.  Have student select "Illinois App Groups"
  6.  Student will see: You are not an admin of any groups.

Expected behavior
Students who have permission to create Events in the Ill App Admin Dashboard, and are Admins of Group(s) should be able to see their groups in order to link their events to their groups.

Additional context
Events Calendar BB 1.67.0 prod.
