### ISSUE TITLE
[BUG] At a privacy level 3, can't access Sign In/Sign Out under Profile

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4103]
When viewing the app at privacy level 3, a user can only see "Who Are You" under Profile and NOT "SIgn In/Sign Out."

I expect to see "SIgn In/Sign Out" under Profile at all privacy levels 

Dev 6.0.4

https://github.com/rokwire/illinois-app/assets/1044905/b95d9b63-3dd0-4d8c-8085-463dc1bd93be

**Comment by mihail-varbanov** [comment]
@vburgett, this behavior is by design. Authentication feature is available only to privacy levels 4 or 5.

**Comment by mihail-varbanov** [comment]
Hi @vburgett,

I consider that the current behavior most probably does not bring a good user experience. It is inherited from the past where the user UI content was dynamic and depended on miscellaneous factors like privacy level, profile role (student, alumni, etc.), logged status and so on. This content generally varies and the user is never sure when a given feature is available.

In my opinion it is much better to keep the UI content permanent, and if a given feature is not available and the user attempts to use it to display an appropriate message. In the current case, we should always keep the Sign In section available and visible, and if the user tries to sign in to explain why he or she cannot do this - due to the privacy level that he/she has set. This should not be done just for a single or few locations in the application. We need to make a complete scan through the entire app content, find all UI components whose availability depends on different settings, and decide how to proceed in each single case. This is a good task for some next major release, but not for the 6.0.

CC @pmarkhennessy

**Comment by vburgett** [comment]
Reopening this for the winter release.

**Comment by mihail-varbanov** [comment]
This must be resolved in version 6.1.17.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov. It seems to be working well in 6.1.17. Can we adjust the pop-up message when a user tries to sign in with a privacy level 1, 2, or 3 to read:

To sign in, set your privacy level to 4 or 5 under Settings. 

Please underline the text "set your privacy level" and make it a link to Settings > My App Privacy Settings.

![Screenshot_20241112-154901](https://github.com/user-attachments/assets/6d674587-d283-4b07-af28-04fba1d68b97)

**Comment by mihail-varbanov** [comment]
Hi @vburgett, the message is updated in 6.1.18.

**Comment by vburgett** [comment]
Confirming as complete in 6.1.25 on dev. Thank you, @mihail-varbanov!
