### ISSUE TITLE
[BUG] Privacy level 5 not requiring NetID sign in

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4107]
I can set my privacy level to 5 when I am not signed in with my NetID. 

Privacy levels 4 and 5 should require a NetID sign in. 

https://github.com/rokwire/illinois-app/assets/1044905/5e3b6f41-7170-4c8e-b227-9755a3099e5f

**Comment by mihail-varbanov** [comment]
@vburgett, login state (on/off) and privacy level (5 / below) is not one-to-one correspondence. For example, you can have privacy level 5 and logout. In this case we will not automatically decrease the privacy level. Or in other words, having privacy level 5 and being logged out is a valid state. That's why we should not require the user to login if the privacy level is increased to 5, because this is a valid case (I would even guess that this will be quite confusing the users). The only relation between the login state and privacy level is that you cannot be logged in and have a privacy level below 4 at the same time, and that's all.

CC @pmarkhennessy.
