### ISSUE TITLE
[USABILITY] Illinois Assistant Keep History Until Users Clears It

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4129]
Thank you for your work on #4089, @dobromirdobrev. Can we adjust the clearing logic to the following?

- the Illinois app should display a user's Illinois Assistant history until they "Clear all"
- The assistant thread history should be display for the user from app session to app session (closing out and re-opening the app)  
- The assistant thread history should display for the user after signing out and signing back into the app

**Comment by dobromirdobrev** [comment]
@vburgett ,
Showing all history is implemented. However we need a new backend API to remove all the messages. So this issue is dependant on https://github.com/rokwire/assistant-building-block/issues/36. Until then we will show "Not implemented, yet" message when the user taps on "Clear All".

The portion with all the history is available in version 6.0.13. Deleting the history will get available once the above issue is resolved.

**Comment by dobromirdobrev** [comment]
"Clear All" functionality is implemented in version 6.1.1 of the Illinois app.

**Comment by vburgett** [comment]
Will this update also work in 6.0.29?

**Comment by dobromirdobrev** [comment]
> Will this update also work in 6.0.29?

Yes, it will.

**Comment by vburgett** [comment]
Confirming as working in 6.0.29. Thank you!
