### ISSUE TITLE
[FEATURE] Updates to Recently Viewed Favorite Widget and Panel

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4132]
Please see the below PDF. If this entire request is not possible for the July 2024 release, please first make the text updates on page one to Browse/Section > Recent.
_Update header to “Recently Viewed” and description to “Revisit your recent app activity.”_ 

[2024-06-RecentlyViewedUpdates-V2.pdf](https://github.com/user-attachments/files/15874169/2024-06-RecentlyViewedUpdates-V2.pdf)

**Comment by mihail-varbanov** [comment]
Hi @vburgett,

[2024-06-RecentlyViewedUpdates-V2.pdf](https://github.com/user-attachments/files/15874169/2024-06-RecentlyViewedUpdates-V2.pdf) is achievable for the upcoming release with some minor adjustments.

I am not sure if you placed the "Browsing History" entry in the Profile instead of Settings panel by purpose or accidentally. We both know that it was a long journey where different settings flew across these panels. At the end we moved almost everything to Settings.

From the other hand we store browsing history on the local device storage, not in the Rokwire cloud service. This means that if the same user uses two different devices, the browsing history could differ between them. Putting "Browsing History" setting in the Profile panel assumes that it will take effect in the user's profile on the Rokwire cloud service, affecting all devices that the user uses, similarly to Favorite widgets for example. Moving the browsing history storage from the local device to the Rokwire cloud service is not such a quick and simple task, that I am not sure if it is even achievable for the July release. That's why I decided to move the Browsing History setting switch to the Settings panel (instead of Profile panel), where we maintain similar settings like this, and to keep the storage of browsing history on the local device unchanged. This is what I did, applying some minor updates to your initial design to match the common look and feel of the settings pages.

It was not intended in the design but I added some confirmation prompts before resetting browsing history to avoid accidental deletion, that you might want to adjust.

This is available in version 6.0.14.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov. It works great in 6.0.14. Is there a reason the text "Browsing History" needs to be repeated under the "My Browsing History" dropdown menu? It appears redundant.

**Comment by mihail-varbanov** [comment]
@vburgett , It repeats because this is the common style of Settings pages.

**Comment by vburgett** [comment]
If you can, please delete the text "Browsing History" above the toggle.
If you can't, please close the ticket.
 
![Screenshot_20240626-131950~2](https://github.com/rokwire/illinois-app/assets/1044905/1acfa5f0-e588-4857-90d4-08bf18d46040)

**Comment by mihail-varbanov** [comment]
@vburgett, I agree that it does not bring any additional info. From the other hand Research or Device Calendar setting pages fall in the same case. That's why I decided not to make an exception for the Browsing History page.

Anyway, I can remove the heading and I did it, available in version 6.0.15.

**Comment by vburgett** [comment]
I agree about the examples you gave. We can continue to get settings cleaned up. 

I can confirm this ticket is now complete with 6.0.15. Thank you, @mihail-varbanov!
