### ISSUE TITLE
[USABILITY] New strings.en.json File

### ISSUE THREAD

**Issue by bstandard** [rokwire/illinois-app#4137]
The new attached version of strings.en.json includes changes for consistency and to clarify functionality in 6.0.

Updated to add new version of the file with changes to line 3523.

[strings.en.json](https://github.com/user-attachments/files/15905584/strings.en.json)

@vburgett

**Comment by mihail-varbanov** [comment]
Hi @bstandard,

1. The resource strings files are maybe the most modified source files of the app. Currently there are too many accumulated changes since the version of strings.en.json from June 13-th that you seem to have started working on. In the future you will make things much easier for us if you make a fork of the "develop" branch, make your changes and then create a pull request to the "develop" branch, that we will review and merge. This will make the process of merging our simultaneous work much easier.

2. You probably noticed that there are also Spanish and Chinese translations of strings.en.json. I am not sure what the translators would do when the time for translation comes - translate everything from starch using the latest strings.en.json, or translate only the updated strings in the existing translations. That's you when we modify some string entry that is already translated, we take care to replace the translated string with its English source text, so that the translators would easily locate the entries that need to be translated.

3. I have now integrated your changes into strings.en.json, I hope I did not miss anything while I merge the differnet updates of this resource. Please check if everything is fine with the latest content on develop branch and close this issue if so.

**Comment by bstandard** [comment]
1. Thanks for laying out a better process, @mihail-varbanov. I hope the new pull request will make these next few corrections easier to manage. Let me know if I should do anything differently next time. With the pace of development changes, it's difficult to get all the pieces synced and everyone aware of the best workflow.

2. For the Chinese translation for 5.1. the translator looked at only the updated or new strings. For the Spanish translation for 5.1. the translator was new and started from scratch. I don't know how this round of translations will work but let me know if I can make that process simpler.

3. I diffed the files but it's possible that some app changes will require other updates. Thanks for managing the multiple versions of the file.
