### ISSUE TITLE
[BUG] "Add Cover Image" button is displays on top of cover image

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#4150]
**Describe the bug**
Added a cover image display along with the button "Add Cover Image" in Create a Group screen

**To Reproduce**
1. Install the app
2. Navigate to Group
3. Tap on "+" icon to create a group and Add a cover image 

Actual Result 
Added cover image is displayed on the screen. But the button "Add Cover Image" is visible on top of the added image.
 

**Expected behavior**
The button "Add Cover Image" should not display once the image is added in the group

**Screenshots**
![Cover image](https://github.com/rokwire/illinois-app/assets/26231179/2ff076a1-502c-4462-989d-afc918c34ba0)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]

 - Version [e.g. 6.0.6]

**Comment by TodorBachvarov** [comment]
Hi @Priyaravi8, If we remove this button the user wont be able to change his image if he already made a selection (Example: User tap Add Image -> Select Image -> Comes back to GroupCreatePanel -> but he don't like the image -> he will have to close the panel and start over in order to change the image). 
I can suggest to change the button text from "Add Image" to "Edit Image" when the user makes selection (same as is PostCreatePanel when user creates group post/message).

**Comment by TodorBachvarov** [comment]
I've implemented my proposal in version 6.0.15

**Comment by Priyaravi8** [comment]
This is fixed.
