### ISSUE TITLE
[BUG] Notification Preferences: Can't Toggle Back on MyMcKinley notification settings

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4287]
I can not toggle MyMcKinley notification settings back on.

1. Go to Settings > My Notification Preferences
2. Toggle off the New MyMcKinley Appointment and Appointment Reminder settings
3. Try to toggle the New MyMcKinley Appointment and Appointment Reminder back on and see how they won't turn back on
4. Make sure Event Reminders is toggled on
5. Toggle on "Pause All Notifications"
6. See how unpausing all notifications remembers your previous notifications settings for Athletics and Groups but not for Events.

I expect to be able to toggle on and off My McKinley notifications. I expect Event Reminders to stay toggled on after I unpause all of my notifications.

v6.0.27 prod 
iPhone 13 Pro, 17.5.1
This is _not_ an issue on v.6.032 prod, Android 14, Pixel 6

https://github.com/user-attachments/assets/d6c8c450-176c-4bd1-96d4-613780e9dd1b

**Comment by mihail-varbanov** [comment]
@vburgett, there are issues in notifications prefs that need deep cleanup. What I did now is rather some improvements and small fixes.

Since switching some settings are asynchronous operations at the moment we display progress indicators for them. I believe this was the reason for the issue in point 3 from your list.

The issue in point 6 was a bug and it should be fixed now.

These all are available in version 6.0.35.

**Comment by vburgett** [comment]
Confirming that this issue is fixed in 6.0.36 on an iPhone. Thank you!
