### ISSUE TITLE
[FEATURE] Text search for campus buildings

### ISSUE THREAD

**Issue by aidanhenry** [rokwire/illinois-app#4290]
Users would like to be able to search for a building by typing a name or keyword. This feature will exist as a button map when Campus Buildings is selected.

**Comment by mihail-varbanov** [comment]
Hi @vburgett,

I wondered if there is any specification about this feature request? What @aidanhenry implemented till now does not look quite good to me, from UX perspective:

![Screenshot 2024-09-05 at 12 30 24 PM](https://github.com/user-attachments/assets/1b5794a2-43ba-407e-b656-5c42ad372d73)

The Search control takes a vertical space, usually containing filtering controls for other Map types (Events and Dining Locations), that gives a large empty space and a single button at right. I have no idea where this button could be better positioned, so that it would not take so much empty space. I was thinking about placing it in the line above, next to the Map types dropdown selector, but I am not sure this would look well. What do you think?

Also, please note that Campus Buildings is the only resource that is available only in the Map tab. While all other location types are available also from a given app section in the Home tab, there is no support for Campus Buildings and Therapist buildings (which are just a subset of all Campus Buildings) there. What I mean is that if we add the corresponding entry(s) somewhere among the Sections, we will have a list view of all buildings, and we could add the search control there in some more natural way.

**Comment by vburgett** [comment]
@mihail-varbanov below is where we were originally headed. Do you foresee any issues with changing the dropdown menu to a filter?
![Screenshot 2024-09-05 at 7 18 15 AM](https://github.com/user-attachments/assets/49650872-3e92-47fd-8e5d-03dcea24d421)

**Comment by mihail-varbanov** [comment]
@vburgett, this is technically possible but it is not a quick change at all. In fact, this is a serious redesign of the Map panel.

Just to confirm that I understand well, In "Map Filters" panel:

1. If the "Events" is the selected location, we will fill below the location control all Event Filters, e.g. Date & Time, Event Type, Event Category, College School Unit and Department.

2. If the "Residence Hall Dining" is the selected location, we will fill below the location control all Dining Filters, e.g. All/Open Now and Payment Type filter.

3. If anything else is the selected location we will not add any filters because the other map (location) types currently do not support any filter. In your screenshot, the Campus Buildings and Amenities controls are currently not supported (but this does not mean that we would not add such in the future).

Оne of the difficulties that I see is Event Filters. They are implemented in a shared and reusable panel for attribute selection, that is also used by Groups, and is expected to get used by other application items in the future. It was really hard to inject into this shared panel for attributes selection the Event specific filters (that are not attributes!) like Date & Time or Event Type. Embedding its content as a fragment of another panel is a very complex task.

Anyway, the screenshot that you sent defines a totally different task than just adding text search for campus buildings, i.e. the right place of this thread would be a separate git issue titled something like "Map panel redesign", for example.

@pmarkhennessy, please take a stand where we will go: just adding search capabilities for campus buildings or start implementing the Map panel redesign. I do not know when the next public release of UIUC 6.0 is planned but this task, as it is currently defined, could take a few weeks.

**Comment by mihail-varbanov** [comment]
@vburgett, thanks for this clarification. Then as a temporary resolution I will leave the search button where it is now (unless you have a better idea), and will handle the buildings text search.

**Comment by mihail-varbanov** [comment]
@vburgett, this should be resolved in version 6.0.41.
