### ISSUE TITLE
[BUG] MTD Bus Pass Incorrectly Marked as Already Displayed on Another Device; Wallet Becomes Stuck

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#4297]
**Describe the bug**
"This MTD this bus pass has already been displayed on another device..." in Wallet >> Bus Pass even though the app is not open on any other devices. Tapping "OK" on the message does not clear it and other Wallet features (e.g., Illini ID, Meal Plan, Illini Cash) cannot be accessed. The app returns to Home and Wallet gets stuck on Bus Pass with the MTD buss pass message. Screen recording included below.

**To Reproduce**
1. Select Wallet >> Bus Pass
2. See error "This MTD this bus pass has already been displayed on another device. Only one device can display the MTD bus pass per Illini ID." 
3. Select Home and other features in Home, or Map
4. Reselect Wallet
5. Same error as 2 displays

**Expected behavior**
I expect the bus pass to display when it's not displayed on another device. If the bus pass is displayed on another device, I expect the message to clear once I tap on "OK" and then I should be able to access other Wallet features, in addition to other components in the app (e.g., Home, Map).

**Screen recording**
https://github.com/user-attachments/assets/0fe1459d-134b-42a1-85ed-fe455795fcdd

**Smartphone (please complete the following information):**
 - Device: Android
 - Version: 6.0.34 prod

**Comment by mihail-varbanov** [comment]
This issue refers multiple problems:

_"This MTD this bus pass has already been displayed on another device..." in Wallet >> Bus Pass even though the app is not open on any other devices._ 
This is most probably a backend issue and needs to be resolved separately.

_Tapping "OK" on the message does not clear it and other Wallet features (e.g., Illini ID, Meal Plan, Illini Cash) cannot be accessed. ..._
This is a client issue and it was resolved in version 6.0.36. Taping OK just dismisses the message instead of closing the entire Wallet panel.

Additional comment:
We display alerts from other Wallet pages as well, for different reasons. For example, in the Illini ID page we could alert "No Illini ID information found. You may have an expired Illini ID. Please contact the ID Center." (that is my case as I have never had iCard). While this behavior was OK before when each Wallet page had been presented as a standalone panel, now it does not bring good UX for me. It is very annoying each time to close it when switching Wallet pages. I think we should rather display some status/error text inside the Wallet page instead of creating an alert. CC @vburgett.

**Comment by vburgett** [comment]
_display some status/error text **inside the Wallet page** instead of creating an alert_
@mihail-varbanov I agree.
