### ISSUE TITLE
[BUG] Healthy Illini Podcast Links Broken

### ISSUE THREAD

**Issue by bstandard** [rokwire/illinois-app#4301]
Links to the Healthy Illini Podcast are broken.

From Home > Sections > Wellness > Healthy Illini Podcast, clicking on the arrow does nothing. See the screenshot.

![hip-main](https://github.com/user-attachments/assets/fbf0dd12-5432-40e2-843b-e0c0e91626a5)

From Home > Sections > Wellness the menu item under Wellness Resources doesn't go anywhere. It's a blank screen. See the screenshots.
![hip-wellness](https://github.com/user-attachments/assets/c99e051d-2413-4d71-9bd6-da8c878fe478)
![hip-wellness-blank](https://github.com/user-attachments/assets/51bdcb2f-0269-4f79-85b5-5768d7adfb0f)

Both places should link to the Campus Guide item with id 158589f4-9ed4-4728-b1ff-e1754cfe7939 that appears under Home > Sections > Campus Guide > Complete Campus Guide > Health & Wellness > General Support > Healthy Illini Podcast. See the screenshots.
![hip-campus-guide](https://github.com/user-attachments/assets/5f0af46d-22de-45ec-a1fc-86b1de6653e2)
![hip-admin](https://github.com/user-attachments/assets/1e44bea4-6cbb-4769-8e08-1445015e5ace)

Android 13 and iOS 17.4.1
v. 6.036 prod

@vburgett

**Comment by mihail-varbanov** [comment]
Hi @bstandard,

The problem comes from the fact that someone removed the following entry from `wellness_resources` category in content service:
```
{
  "favorite": 0,
  "id": "podcast",
  "type": "large",
  "url": "edu.illinois.rokwire://rokwire.illinois.edu/guide_detail?guide_id=158589f4-9ed4-4728-b1ff-e1754cfe7939&analytics_feature=wellness"
}
```
Both from `Home/Sections/Wellness/Healthy Illini Podcast` and `Healthy Illini Podcast` dropdown entry from `Wellness` panel refer to this item (by its id `podcast`) to access the target guide detail item defined by its `url` field.

I have no idea who and why did remove this entry from `wellness_resources` category. For now I just added it back, both on production and dev, and all links had been restored for the existing (already released) app, i.e. no source code updates were needed. The only "side" effect of this fix is that `Listen to the Healthy Illini Podcast` entry appeared back in the wellness resources list, accessible via `Home / Sections / Wellness / Resources`. If this is a not desired behavior I will have to make source code updates to change the way that `Healthy Illini Podcast` command entry accesses the target guide item that it needs to launch. Let me know please if the current configuration is OK, or I will have to make the code changes.

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, this again raises the question about keeping under source control all the content data that Illinois app accesses. ^

**Comment by vburgett** [comment]
@mihail-varbanov @pmarkhennessy I bet I caused this issue when I was trying to figure out how the Campus Guide works.

**Comment by bstandard** [comment]
As long as @vburgett is satisfied with the duplication of the Healthy Illini Podcast entry under Home > Sections > Wellness > Resources from both the top dropdown menu and as an entry under "I want to learn about HealthiestYou Telehealth" then this works.

**Comment by vburgett** [comment]
I am ok with this redundancy for now, @bstandard.
