### ISSUE TITLE
[BUG] Message Conversation UI Updates and Bug Fixes

### ISSUE THREAD

**Issue by manav2modi** [rokwire/illinois-app#4536]
Message Conversation UI Updates and Bug Fixes:

- [x] Sending messages is not updating the conversation list 
- [x] Conversation panel is not auto-scrolling to the bottom (most recent message) after loading messages
- [x] Conversation messages are paginated but only the first page is ever loaded

- Messages Panel
    - [x] Add search bar to search for conversations by name as discussed
    - [x] It looks like the “Mute” option is missing from the conversation selection menu
    - [x] New Message button on messages panel has line break. Probably just needs a smaller font
    - [x] Let’s hide the “Mark all as read” button until this functionality is implemented
- New Message Panel
    - [x] The search bar on the recent tab doesn’t seem to work as intended. Is this hooked up to the conversations API to filter by name? If so we probably should use it like that here.
    - [x] Hide the filter button on the Recent tab since it is not functional here
    - [x] Match checkbox state between Recent tab and All users tab (ie. If I select JP on the recent tab he should also be selected on the All Users tab and vice versa)
    - [x] The drop-down arrows should be removed from the Recent tab since no details are available there
- Conversation Panel
    - [ ] Message notifications
        - [ ] Refresh page when notification is received for currently visible conversation
        - [ ] Only show push notification if not currently looking at the related conversation
        - [ ] Tapping notification should deep link to the conversation panel. We probably need to define the deep link string and share it with Petyo to add to the back-end when the notification is sent.
    - [ ] Image attachment button doesn’t work on the conversation panel. We should reference the group messaging functionality for this.
    - [x] The message textfield on the conversation panel should not have the carrot to the left that expands to show the image button and the microphone button. Check the designs for the correct layout (image button on left, microphone overlayed to the right of the text field). For the microphone button please look at the assistant tab to see a very similar design that you should be able to reuse.
    - [ ] We should make sure that the scroll is inverted on this panel. At the moment if you have a long list of messages in the conversation it shows the first one at the top and you need to scroll down to see the most recent. Check out the assistant tab for an example of the expected behavior
    - [x] Ideally the sent message should appear immediately in the conversation after pressing the send button rather than showing a loading indicator

**Comment by shurwit** [comment]
Hi @manav2modi , I unchecked a few boxes above that I hope you can take a look at in addition to the new feedback below:
- Reopened:
  -  The drop-down arrows should be removed from the Recent tab since no details are available there: There is still a dropdown arrow appearing next to messages with more than one user
  -  We should make sure that the scroll is inverted on this panel. At the moment if you have a long list of messages in the conversation it shows the first one at the top and you need to scroll down to see the most recent. Check out the assistant tab for an example of the expected behavior: While we do now autoscroll to the bottom when the panel opens, the scroll is still not inverted like I believe it should be. Again please check the assistant panel to see how it is working there
- New
  - I'm having trouble testing pagination as it seems like the limit per page is high. Please just double check that pagination is working as expected in the conversation panel, especially after applying the inverted scroll. We would expect the first page to load with the latest message at the bottom of the screen, then the user can scroll backwards and when they reach the top of each page it should load the previous page and show the older messages above.
  - The loading indicator seems to be centered on this page. Ideally we would put the loading indicator above the last element in the scrollable list whenever a page is loading
