### ISSUE TITLE
[BUG] Student Guide: "New Students" topic section appears, despite there not being any items to list

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#607]
**Description of Bug**
Illinois app v 2.6.6-dev-debug.apk (set to Production environment)

The topic "New students" appears in the Student Guide, despite all subtopics having been removed.

**Reproduce** 
Go to **Illinois app > Browse > Student Guide** 
Scroll to "New students"

**Expected behavior**
The "New students" topic should not appear. 

We are no longer using the "New students" topic to classify information pages in the guide.

The "New students" topic does not appear in the shipping version of Illinois app (v 2.5.9 ios; android)

**Comment by joegrohens** [comment]
Still true in 2.6.10 apk - pointed at prod env

Also, the dev env does not reflect updates we have made to the Student Guide (through Content Manager pointed at Prod). I presume (hope) that is normal.

**Comment by joegrohens** [comment]
This student guide bug is still present in prod release candidate 2.6.14

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,
This should be fixed, now. The problem was that there was a guide record without "section" field and with "category": "New students". This made Illinois app to show it with empty content but the admin app was not showing it. Now the admin app was fixed to display the same as the Illinois app, so that admin user is able to remove such guides. Also we removed this from guides records in production. Now "New students" does not exist in prod environment. Please, verify it on your end with the latest available Illinois app (e.g. 2.6.14).

As regards to your comment:

> Also, the dev env does not reflect updates we have made to the Student Guide (through Content Manager pointed at Prod). I presume (hope) that is normal.

Yes, this is normal. Dev and Prod are two different environments. They point to different DBs and so their student guide records are different. So, if you change something in dev, it will reflect only in dev. The same goes for prod environment.
