### ISSUE TITLE
[BUG] line breaks missing in event details

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#692]
**Describe the bug**
Event ID 610c172873bcf8000a95a996 has line breaks in Events Manager that do not appear in the app.
It's called College Meetings and is part of the Welcome Week 2021 ... super event.

Here's how it appears in Events Manager:
<img width="825" alt="Screen Shot 2021-08-13 at 3 38 18 PM" src="https://user-images.githubusercontent.com/11352701/129416195-d702a39b-516e-4409-8359-40bd84f15f21.png">

Here's how it appears in the Illinois app:
![IMG_3763](https://user-images.githubusercontent.com/11352701/129416219-8cc8d27e-0e00-444c-ba18-3847a11f1977.PNG)

**Expected behavior**
The line breaks should be shown in the app

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome latest version

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15 and iOS 14
 - Version 2.6.16 and 2.6.18

**Comment by dobromirdobrev** [comment]
Hi @isaac-galvan ,
The problem is that the events service sends new line symbols like `\r\n` but the client expects html content. The html flutter widget does not handle these symbols. That's why we changed the client so that to replace these symbols `\r\n` with the symbol for new line in html '<br/>'.

This is done in version 2.6.19 and 3.0.0


cc @sandeep-ps , @pmarkhennessy
