### ISSUE TITLE
[BUG] Unable to create a new event in a group

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#903]
**Describe the bug**
Using build 3.0.39, received "Unable to create Event" message when trying to create a new event in a group. I tested with both a pre-3.0 group and a brand new group. 

**To Reproduce**
1. Go into a group
2. Click on + to add an Event
3. Choose to "Create new event"
4. Enter the required fields
5. Save

**Smartphone**
 - Device: Google Pixel 2 XL
 - OS: Android 11

**Comment by mihail-varbanov** [comment]
Hi @sandeep-ps,

```
curl -X POST \
-H "Accept: application/json" \
-H "content-type: application/json" \
-H "authorization: Bearer ..." \
-d '{"title":"Group Event 1.1","longDescription":"Misho Test Group 1 / Event 1","imageURL":"https://rokwire-images.s3.us-east-2.amazonaws.com/event/tout/1903c1f8-3d52-11ec-b750-0a58a9feac02.webp","location":{"description":""},"startDate":"2021/11/18T09:15:00","startDateLocal":"2021-11-18T03:15:00","endDate":"2021/11/18T09:45:00","endDateLocal":"2021-11-18T03:45:00","category":"Athletics","titleURL":"https://www.yahoo.com","registrationUrl":"https://www.google.com","cost":"","allDay":false,"recurringFlag":false,"isVirtual":false,"createdByGroupId":"fc603531-3d51-11ec-b683-0a58a9feac02","isGroupPrivate":false,"isEventFree":true}' \
https://api-dev.rokwire.illinois.edu/events
```
returns 401
```
{
  "detail": "Invalid token",
  "status": 401,
  "title": "Unauthorized",
  "type": "about:blank"
}
```

The authorization token that I apply is valid, fresh, etc. and I use it successfully from several other places.

**Comment by pmarkhennessy** [comment]
@shurwit

**Comment by shurwit** [comment]
Hi @mihail-varbanov, I believe this is a permission issue. Unless you assigned yourself the necessary permissions in the Core BB, this is the expected result. After we deploy the changes and handle the necessary configurations for https://github.com/rokwire/core-building-block/pull/288, I believe this endpoint should work as expected. Please let me know if you have any questions. Thanks!

**Comment by sandeep-ps** [comment]
Sorry, I missed responding to this GitHub issue earlier. 

Thanks for clarifying this, Stephen.

**Comment by mihail-varbanov** [comment]
Hi @shurwit, then I am assigning this issue to you. Please reassign it back to @kpecknold when this update gets deployed.

**Comment by shurwit** [comment]
Hi @mihail-varbanov, I believe I have done the necessary configurations to get the permissions working as expected. I was not able to test the groups/roles mapping from the Shibboleth token directly since my Shibboleth account does not have any of these groups, however I did verify that the roles will work if they are assigned correctly. 

@petyos I added a couple of roles and permissions to get this working. You may notice that the permissions look like they should be roles. This is because of the way the permissions are defined for the events service (https://github.com/rokwire/rokwire-building-blocks-api/blob/260f7dc5fc061028794a6848a15fbdbe8a25f856/lib/auth-middleware/auth_middleware/__init__.py#L42). At some point, we may want to consider reworking these to be more granular as we discussed.

@mihail-varbanov @petyos could one of you please verify that the roles mapping from the Shibboleth token is working as expected and that you are now able to create group events? Thanks!

**Comment by mihail-varbanov** [comment]
I tried it but I am still getting 401 unauthorized. I do not know if my UIUC account misses this right, or this is an issue in Core BB service.

**Comment by shurwit** [comment]
> @shurwit, I tried it but I am still getting 401 unauthorized. I do not know if my UIUC account misses this right, or this is an issue in Core BB service.

Hi @mihail-varbanov, thanks for testing it out. It looks like when I manually updated the roles in the database it did not cause the accounts to update appropriately. I have manually updated the `groups access` role associated with each account to be consistent. I believe you should now be able to make this request successfully. I apologize for the oversight. If you are still not able to make this request successfully please let me know. Thanks again!

**Comment by mihail-varbanov** [comment]
Hi @shurwit, thanks, it works now.

**Comment by mihail-varbanov** [comment]
@kpecknold, I am assigning this to you as the problem should be already fixed on backend. You should be able to create group events if your account has rights for this.
