### ISSUE TITLE
[FEATURE] Improve log data

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#95]
**Is your feature request related to a problem? Please describe.**
Click stream logs coming from the Illinois app needs to be improved to help debugging. For example, it needs to have app_id value set so that the Illinois app logs can be easily distinguishable from the Safer Illinois app logs.

CC: @wryanthomas

**Describe the solution you'd like**
1. `app_id` value needs to be set for all log entires
2. `user_uuid` needs to be sent for all log entries after a Non-PII profile has been created.
3. `session_uuid` needs to be sent for all log entries

**Comment by mihail-varbanov** [comment]
These are done.

User and session UUIDs still can be null in the very first few analytics events. The reason is that we need to initialize first the internal services that analytics depends on (e.g. config), but they generate analytics events while being initializing. There is a resolution of this tweak (e.g. cache events before analytics initialization) but I am not sure the development effort for this worths.

**Comment by sandeep-ps** [comment]
Closing this as no additional requests have come in of late. Thanks.
