### ISSUE TITLE
[BUG] Rejected group displays under My Groups

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#958]
**Describe the bug**
The group which is rejected is displayed in Users My Group 

**To Reproduce**

1. Install the new version of the Illinois app
2. Go to groups feature
3. Send a "Request to Join" to a Private group (Eg Group A)
4. Admin of the Private group (Group A) rejects the request.

**Actual Result**
Though the user is rejected from the Private group (Group A), the group (Group A) is displayed under My Group to the users

**Expected behavior**
The rejected group (Group A) should not show up in users My group.

**Smartphone (please complete the following information):**
 - Device: [e.g. Andoid]
- Version [e.g. 2.7.7]

**Comment by mdryankov** [comment]
Thus is quite a good question and the solution depends on what we have to achieve, because currently the rejected user is still a member of the group but its state is "rejected"?

1. If we want control over this situation. Then the Groups BB will keep setting the member as rejected and we will get out such users from my groups results. If the user wants to re-join - the administrator of the group must remove it furst and then try to rejoin
2. If we don't want such control. Then the user membership record will be deleted instead of marked as rejected. 

@pmarkhennessy @johnmpaul @Priyaravi8  what do you think?

**Comment by mihail-varbanov** [comment]
Fixed in Illinois client version 2.8.1.
